{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-rx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ftspq6ko35hobkdw3tuesrnjqa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "4.0.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-1.0.0.aar",
          "url": "epoxy-rx-1.0.0.aar",
          "size": 34366,
          "sha512": "5f64618b3bf76695cadab0b867cfaeda7bf8cb1af6d3cefcd6cebb576ab5c677f378f8bdef5f289a2a7b0e2b643537cce56bc44565ff848e352dbc8585a3dca2",
          "sha256": "6b96bed04c11458f12a14f85e94ce6ccf5ecb118454994caa3ff6ca11753a787",
          "sha1": "059a705d49794a41ecd55cfdc1d688777a7a19ea",
          "md5": "630fa69e62a793e71221db00439a90a2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "4.0.0-beta4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-1.0.0.aar",
          "url": "epoxy-rx-1.0.0.aar",
          "size": 34366,
          "sha512": "5f64618b3bf76695cadab0b867cfaeda7bf8cb1af6d3cefcd6cebb576ab5c677f378f8bdef5f289a2a7b0e2b643537cce56bc44565ff848e352dbc8585a3dca2",
          "sha256": "6b96bed04c11458f12a14f85e94ce6ccf5ecb118454994caa3ff6ca11753a787",
          "sha1": "059a705d49794a41ecd55cfdc1d688777a7a19ea",
          "md5": "630fa69e62a793e71221db00439a90a2"
        }
      ]
    }
  ]
}
