{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-rx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "x4mfbbcdrvdo5a2wp5edi3dnau"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "4.0.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-1.0.0.aar",
          "url": "epoxy-rx-1.0.0.aar",
          "size": 34451,
          "sha512": "57af2039e06730f3aa8c5f8d10ef5373ba43218ea3b62d9c47a6f6e46b18ffdd290083dcb7b13326dc7181595331298c224bf25da849f9421d058e2514eb4aad",
          "sha256": "cb43b17a8bee07a75da591a19bde3e1ac3dda02b9ed7bfe464196750c7c93dd5",
          "sha1": "265000c007e4313d0be993cc399cca242dd2a2be",
          "md5": "e1a90e647eb7958a3ac1c5e189a326ba"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "4.0.0-beta4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-1.0.0.aar",
          "url": "epoxy-rx-1.0.0.aar",
          "size": 34451,
          "sha512": "57af2039e06730f3aa8c5f8d10ef5373ba43218ea3b62d9c47a6f6e46b18ffdd290083dcb7b13326dc7181595331298c224bf25da849f9421d058e2514eb4aad",
          "sha256": "cb43b17a8bee07a75da591a19bde3e1ac3dda02b9ed7bfe464196750c7c93dd5",
          "sha1": "265000c007e4313d0be993cc399cca242dd2a2be",
          "md5": "e1a90e647eb7958a3ac1c5e189a326ba"
        }
      ]
    }
  ]
}
