{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "4fzlpzibufh27dbdqnnzrl5cem"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 25062,
          "sha512": "5a3f023592600b9234e9f432d08dd5706848f660fcd0db829d3e957bb40290b27d9357e8b3751185c380f63b45b3f1d94debba05984d9a9bc6cb55825dfed653",
          "sha256": "48e5915bce60e8263df606ef1588d59e4c7b1fad4c25a63085ab054ad7498319",
          "sha1": "fe98c271965563c1b2a4ff61f1111094d376fa2d",
          "md5": "2c7a5bcf30c66f6bdd261f36bcc2a2d3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 25062,
          "sha512": "5a3f023592600b9234e9f432d08dd5706848f660fcd0db829d3e957bb40290b27d9357e8b3751185c380f63b45b3f1d94debba05984d9a9bc6cb55825dfed653",
          "sha256": "48e5915bce60e8263df606ef1588d59e4c7b1fad4c25a63085ab054ad7498319",
          "sha1": "fe98c271965563c1b2a4ff61f1111094d376fa2d",
          "md5": "2c7a5bcf30c66f6bdd261f36bcc2a2d3"
        }
      ]
    }
  ]
}
