{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "vjhgf3c57za5zhl7mpk2mtx24a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 27580,
          "sha512": "acf8f921bbb89591156d080c5aa8845716bdbf60124a4e1c26660d05293d753009444e444d425413842251ccbcb50c243d0c10fc359d54c820f59f8f4729740e",
          "sha256": "219b00ef5a44c34a31eef6417e3871cc60e6b60a6ff80b017b5f2560eaf38c6f",
          "sha1": "649624fd3530082ca4b0a9ae093691f7a2fab42f",
          "md5": "493bf7ac4576db4b2fd8b0f0fc7a722d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 27580,
          "sha512": "acf8f921bbb89591156d080c5aa8845716bdbf60124a4e1c26660d05293d753009444e444d425413842251ccbcb50c243d0c10fc359d54c820f59f8f4729740e",
          "sha256": "219b00ef5a44c34a31eef6417e3871cc60e6b60a6ff80b017b5f2560eaf38c6f",
          "sha1": "649624fd3530082ca4b0a9ae093691f7a2fab42f",
          "md5": "493bf7ac4576db4b2fd8b0f0fc7a722d"
        }
      ]
    }
  ]
}
