{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "vamn7kmqhbcanmnkamshex4lae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 27581,
          "sha512": "a1e3859f589f3943f91cc642717bbde23dceb63347fc4bec5dd8ee758701ed5110e4ce61fcd95d371d9f121e89b174e0b300043b42c7ed3a605dd311ae6a396a",
          "sha256": "ae4668386eb8be9f03da4ea77d451b764b487e9e6bcb005cb727c41c6a5c3e68",
          "sha1": "37780b2da48c44ace994fe5ec481b76f652246ab",
          "md5": "80c7848ac2809e850e9251c7c08f7306"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.aar",
          "url": "common-1.0.0.aar",
          "size": 27581,
          "sha512": "a1e3859f589f3943f91cc642717bbde23dceb63347fc4bec5dd8ee758701ed5110e4ce61fcd95d371d9f121e89b174e0b300043b42c7ed3a605dd311ae6a396a",
          "sha256": "ae4668386eb8be9f03da4ea77d451b764b487e9e6bcb005cb727c41c6a5c3e68",
          "sha1": "37780b2da48c44ace994fe5ec481b76f652246ab",
          "md5": "80c7848ac2809e850e9251c7c08f7306"
        }
      ]
    }
  ]
}
