{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "spring-item-animator",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "va6gft5fezfo7amkonmjursz5u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-item-animator-1.0.0.aar",
          "url": "spring-item-animator-1.0.0.aar",
          "size": 16333,
          "sha512": "1bad122c10b4881a41c0c67eafc4b5b9fa2d8918ea31e7b38112564f8d888889eb57efd4f9a4b613239036a2a4c1848ae26d27eb7731f0baa58a7b47fb6dc1d9",
          "sha256": "f31e97838f36c0d9f2e4acf9deefdcb3abfa28c18b37992fd5d4fd4e3140523c",
          "sha1": "815c37dd0ab525b7b53e25511c00e1366984fb75",
          "md5": "e9a742d0501e4432e324288ac3f890ae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "spring-item-animator-1.0.0.aar",
          "url": "spring-item-animator-1.0.0.aar",
          "size": 16333,
          "sha512": "1bad122c10b4881a41c0c67eafc4b5b9fa2d8918ea31e7b38112564f8d888889eb57efd4f9a4b613239036a2a4c1848ae26d27eb7731f0baa58a7b47fb6dc1d9",
          "sha256": "f31e97838f36c0d9f2e4acf9deefdcb3abfa28c18b37992fd5d4fd4e3140523c",
          "sha1": "815c37dd0ab525b7b53e25511c00e1366984fb75",
          "md5": "e9a742d0501e4432e324288ac3f890ae"
        }
      ]
    }
  ]
}
