{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "spring-item-animator",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3zbqlpvcy5avvnsgeltdb73bqa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-item-animator-master-SNAPSHOT.aar",
          "url": "spring-item-animator-master-SNAPSHOT.aar",
          "size": 16407,
          "sha512": "906dff536883f5ab5f6390d1c65ef34cbc10722f8cbf6ce379b57aa5bda07d6a7b6ba5b6b5a25e64b7e1200378909b640f32eec7bba70c5457a7b2b7cb694983",
          "sha256": "a04ede0b2aace4d193d08d73eaa9cfda6a056721c6db11cd1c5e62c302e01f80",
          "sha1": "9e473137bacd01c4627af6de09ffab445ecf0c1a",
          "md5": "32c4bb77aecc763d3745d107aaccb1c3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "spring-item-animator-master-SNAPSHOT.aar",
          "url": "spring-item-animator-master-SNAPSHOT.aar",
          "size": 16407,
          "sha512": "906dff536883f5ab5f6390d1c65ef34cbc10722f8cbf6ce379b57aa5bda07d6a7b6ba5b6b5a25e64b7e1200378909b640f32eec7bba70c5457a7b2b7cb694983",
          "sha256": "a04ede0b2aace4d193d08d73eaa9cfda6a056721c6db11cd1c5e62c302e01f80",
          "sha1": "9e473137bacd01c4627af6de09ffab445ecf0c1a",
          "md5": "32c4bb77aecc763d3745d107aaccb1c3"
        }
      ]
    }
  ]
}
