{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "colors",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dt5lnliqerfrresoqrdnovhsda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 9948,
          "sha512": "3943e70eecd5cf420ad0de40a6842402df0e584e3899e821f335b0d4e783c16cb72fd4ce175d4e3865016b8b16d460da17cc57a7cd075e6c186ed4b044f4f1a0",
          "sha256": "43fd94462ec91f3762d639c7373c5faae98a0d88849ea7b28ea21b4cc56e50fd",
          "sha1": "b46fe84569763fd60fe087c259e9ff2528c80701",
          "md5": "badadd7c8ae30483e66cc269230a613e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 9948,
          "sha512": "3943e70eecd5cf420ad0de40a6842402df0e584e3899e821f335b0d4e783c16cb72fd4ce175d4e3865016b8b16d460da17cc57a7cd075e6c186ed4b044f4f1a0",
          "sha256": "43fd94462ec91f3762d639c7373c5faae98a0d88849ea7b28ea21b4cc56e50fd",
          "sha1": "b46fe84569763fd60fe087c259e9ff2528c80701",
          "md5": "badadd7c8ae30483e66cc269230a613e"
        }
      ]
    }
  ]
}
