{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "colors",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "va6gft5fezfo7amkonmjursz5u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 5578,
          "sha512": "051cd0e3603dc0e70401f2e1f675afc85b41c3995e5ed3608a7b1644434dad3f9319cf27e497f1f124f61137a06e5dc0c7999ba2563f2c1ad2e72b1b6f4f4a05",
          "sha256": "a73351faf3b051b4ce98eec11d2d130270c91f837e805525d1a9b3961e73e1ae",
          "sha1": "708ec1a8a5b36298af6c11677008e85aac56243f",
          "md5": "120d9e4c47924e1dd5328d38ad0998b6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 5578,
          "sha512": "051cd0e3603dc0e70401f2e1f675afc85b41c3995e5ed3608a7b1644434dad3f9319cf27e497f1f124f61137a06e5dc0c7999ba2563f2c1ad2e72b1b6f4f4a05",
          "sha256": "a73351faf3b051b4ce98eec11d2d130270c91f837e805525d1a9b3961e73e1ae",
          "sha1": "708ec1a8a5b36298af6c11677008e85aac56243f",
          "md5": "120d9e4c47924e1dd5328d38ad0998b6"
        }
      ]
    }
  ]
}
