{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "colors",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6fz4e4md6nf5jk33n4nfyuwfme"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 5570,
          "sha512": "f488589ff0bffe78d092ae6acd25a66360a0b7d9ec4756ce214017743afeb5caf89f6696c77239282edb03a035ebb940b2916c498e2da23659dcdd180bdacda0",
          "sha256": "d249e50b43e2705d8bba30f3db8f5ac5119b780c145c0ec9bf2c84938a069e97",
          "sha1": "479ea85295ab0f815ffd1907193b4ace3f20b8d4",
          "md5": "9989008046f27109d26fefe05db3989c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "colors-1.0.0.aar",
          "url": "colors-1.0.0.aar",
          "size": 5570,
          "sha512": "f488589ff0bffe78d092ae6acd25a66360a0b7d9ec4756ce214017743afeb5caf89f6696c77239282edb03a035ebb940b2916c498e2da23659dcdd180bdacda0",
          "sha256": "d249e50b43e2705d8bba30f3db8f5ac5119b780c145c0ec9bf2c84938a069e97",
          "sha1": "479ea85295ab0f815ffd1907193b4ace3f20b8d4",
          "md5": "9989008046f27109d26fefe05db3989c"
        }
      ]
    }
  ]
}
