{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ce43cls6vvfi5lmnuqjufuwv5a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20418,
          "sha512": "a1eb499318d5ccb2f3577c7c9ed675f09100540513f3dbe6d797c94bdda59add7dc07222f4a26cd3a10c5a6882f0d546be47b9146888f243b72bd59341f539f3",
          "sha256": "4250cdab76702f9d7c7c7b0813573fe17cebe903aa1841d388e2111628902ecd",
          "sha1": "be176ab08b0bc902943f1e990c0a0ff49f2e2aa4",
          "md5": "9d8527250f6e13f814268944bfe039ab"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20418,
          "sha512": "a1eb499318d5ccb2f3577c7c9ed675f09100540513f3dbe6d797c94bdda59add7dc07222f4a26cd3a10c5a6882f0d546be47b9146888f243b72bd59341f539f3",
          "sha256": "4250cdab76702f9d7c7c7b0813573fe17cebe903aa1841d388e2111628902ecd",
          "sha1": "be176ab08b0bc902943f1e990c0a0ff49f2e2aa4",
          "md5": "9d8527250f6e13f814268944bfe039ab"
        }
      ]
    }
  ]
}
