{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "dklignzjincgpk54yjmfetzxfq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20407,
          "sha512": "d27ac30303731ff073684cbe539432f11d9db549416fbd55d85bdec08f61ad3514e45e5e15d32e14a92b060966cc9def4f1a8479bdb8ca133ad5b354eba281fa",
          "sha256": "19154214f631a22883b24275df6a4b587592e698078baadb122a92d5c59fef7e",
          "sha1": "2c2331458515aea311cbf0f18a9e08c0fa0c162b",
          "md5": "2024548204dc44d7f2f5d36fd6d9a218"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20407,
          "sha512": "d27ac30303731ff073684cbe539432f11d9db549416fbd55d85bdec08f61ad3514e45e5e15d32e14a92b060966cc9def4f1a8479bdb8ca133ad5b354eba281fa",
          "sha256": "19154214f631a22883b24275df6a4b587592e698078baadb122a92d5c59fef7e",
          "sha1": "2c2331458515aea311cbf0f18a9e08c0fa0c162b",
          "md5": "2024548204dc44d7f2f5d36fd6d9a218"
        }
      ]
    }
  ]
}
