{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "rikxbsfiwzekpbuqldq3py7xru"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20406,
          "sha512": "9a4bfb9906e416e7d05126e549d8fa6e81fe1b06a911dc2f05b9244d457d486f5ac8d47dff4042d6dfdf2d1b74bf4a252b417df3371753825b7c57e326c16d4d",
          "sha256": "4bec0958677309e1e2be29213d43c7a0a25b3546650ad0f783ea60cd68713d18",
          "sha1": "ee21b4b8e8d25a6a137addff4541ff02c29f4851",
          "md5": "fd47b69a141f6e54d733ef076cbcead0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20406,
          "sha512": "9a4bfb9906e416e7d05126e549d8fa6e81fe1b06a911dc2f05b9244d457d486f5ac8d47dff4042d6dfdf2d1b74bf4a252b417df3371753825b7c57e326c16d4d",
          "sha256": "4bec0958677309e1e2be29213d43c7a0a25b3546650ad0f783ea60cd68713d18",
          "sha1": "ee21b4b8e8d25a6a137addff4541ff02c29f4851",
          "md5": "fd47b69a141f6e54d733ef076cbcead0"
        }
      ]
    }
  ]
}
