{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "x4urdvryg5a3dcvbesv3s7rvnq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-20200310.201649-1.aar",
          "size": 20489,
          "sha512": "aeb9c8a872b2bd627b236b968f7a3b9ca962b7c0321def15ca546efdc440ba555ab9f6df9b43257b613a1d0b38b0e8c23232ace63611b8e73b6769017b38cfe7",
          "sha256": "3b5ee036252847945dc6e19fdab79cbb81ebbe318320c3c55862ca65b3b41b41",
          "sha1": "565eddff8a21824091b6937b932e1cdf2870b440",
          "md5": "243415ce1930f764ea7fecae3abc8f04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-20200310.201649-1.aar",
          "size": 20489,
          "sha512": "aeb9c8a872b2bd627b236b968f7a3b9ca962b7c0321def15ca546efdc440ba555ab9f6df9b43257b613a1d0b38b0e8c23232ace63611b8e73b6769017b38cfe7",
          "sha256": "3b5ee036252847945dc6e19fdab79cbb81ebbe318320c3c55862ca65b3b41b41",
          "sha1": "565eddff8a21824091b6937b932e1cdf2870b440",
          "md5": "243415ce1930f764ea7fecae3abc8f04"
        }
      ]
    }
  ]
}
