{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "oqvocydmkrbzpjpbm3omis5pza"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20823,
          "sha512": "fd3c6685646e195b40fce50ae1c68124dd3e4f9e4429b51043644bc5df94e8938873f57c5207b1d9461866178e248ce8d258ae20595cb2034f78c3dfe81fe8ff",
          "sha256": "d72bd1289f46201131c367e91e12e91352d218e2d914178e17f2722b3c9f71ab",
          "sha1": "15c5772fb2355f1fac0bf4a96422824618f0b5f2",
          "md5": "0cd0fc309e416829a558d90e06ce0ab0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-master-SNAPSHOT.aar",
          "url": "dagger-workmanager-master-SNAPSHOT.aar",
          "size": 20823,
          "sha512": "fd3c6685646e195b40fce50ae1c68124dd3e4f9e4429b51043644bc5df94e8938873f57c5207b1d9461866178e248ce8d258ae20595cb2034f78c3dfe81fe8ff",
          "sha256": "d72bd1289f46201131c367e91e12e91352d218e2d914178e17f2722b3c9f71ab",
          "sha1": "15c5772fb2355f1fac0bf4a96422824618f0b5f2",
          "md5": "0cd0fc309e416829a558d90e06ce0ab0"
        }
      ]
    }
  ]
}
