{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "x3cp7rdjtndptc4l5m7eti34pu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-unspecified.aar",
          "url": "glide-component-icon-unspecified.aar",
          "size": 11625,
          "sha512": "ddae50edef7a97419d3377bf9528325cfb157a6581d61ebca1501087f326ff662efe403faefa9610c3c6a461d42ff77209b23a771d03b077dc52e195888ff876",
          "sha256": "ef899bae74503d0667df414d6add8edc47c815c953a76db7a26ae58c252b6179",
          "sha1": "d7d0b327dd390c8362a44ee65e758ecd107a5f7a",
          "md5": "549572a2af907600bab12781a7186024"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-unspecified.aar",
          "url": "glide-component-icon-unspecified.aar",
          "size": 11625,
          "sha512": "ddae50edef7a97419d3377bf9528325cfb157a6581d61ebca1501087f326ff662efe403faefa9610c3c6a461d42ff77209b23a771d03b077dc52e195888ff876",
          "sha256": "ef899bae74503d0667df414d6add8edc47c815c953a76db7a26ae58c252b6179",
          "sha1": "d7d0b327dd390c8362a44ee65e758ecd107a5f7a",
          "md5": "549572a2af907600bab12781a7186024"
        }
      ]
    }
  ]
}
