{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "5p2g6allanb6howmll52dje3mm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-unspecified.aar",
          "url": "dagger-workmanager-unspecified.aar",
          "size": 20472,
          "sha512": "dea4b80ab3bd867f3c250a40c4f29dfdc48b32b48bc634ea817bb153c60eea583b45777eae1528d3c19a3a107dfc21a2d30665cada34153a1609d80c2c2e7a84",
          "sha256": "f6235edd97ee43fd195e9fa361c90cfa1afdb92a8f97a20bebfb6b830aa98964",
          "sha1": "aad0cb1bdafeec38ed1676d657b2be40ed1cda23",
          "md5": "040583fee91a28e3132adc9d3faee6bf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-unspecified.aar",
          "url": "dagger-workmanager-unspecified.aar",
          "size": 20472,
          "sha512": "dea4b80ab3bd867f3c250a40c4f29dfdc48b32b48bc634ea817bb153c60eea583b45777eae1528d3c19a3a107dfc21a2d30665cada34153a1609d80c2c2e7a84",
          "sha256": "f6235edd97ee43fd195e9fa361c90cfa1afdb92a8f97a20bebfb6b830aa98964",
          "sha1": "aad0cb1bdafeec38ed1676d657b2be40ed1cda23",
          "md5": "040583fee91a28e3132adc9d3faee6bf"
        }
      ]
    }
  ]
}
