{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "h6vh7eofnjcs7brnbe73h6bmve"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-unspecified.aar",
          "url": "dagger-workmanager-unspecified.aar",
          "size": 18366,
          "sha512": "6d0af591fdea040b836bd048e1f7ebe410924d1b75093c35436961d98a5d844ed2d21111111ddb8ea831c55f63f21f77ac4aa5a4611da89923dcbab044f825cc",
          "sha256": "04d5cbdfae5f64168745e3997406a46a50f59ede9d96307c6c9edab89d8b258d",
          "sha1": "05e3f85311605a66b317738bb517a07e33ab4a72",
          "md5": "ee5e781e5430e4a56f3e01d2bb8f8b5f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-unspecified.aar",
          "url": "dagger-workmanager-unspecified.aar",
          "size": 18366,
          "sha512": "6d0af591fdea040b836bd048e1f7ebe410924d1b75093c35436961d98a5d844ed2d21111111ddb8ea831c55f63f21f77ac4aa5a4611da89923dcbab044f825cc",
          "sha256": "04d5cbdfae5f64168745e3997406a46a50f59ede9d96307c6c9edab89d8b258d",
          "sha1": "05e3f85311605a66b317738bb517a07e33ab4a72",
          "md5": "ee5e781e5430e4a56f3e01d2bb8f8b5f"
        }
      ]
    }
  ]
}
