{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "orbit",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "dklignzjincgpk54yjmfetzxfq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "orbit-master-SNAPSHOT.aar",
          "url": "orbit-master-SNAPSHOT.aar",
          "size": 35803,
          "sha512": "e8e627bb131fefba999688fef3d7cf4c103fcc0a9ab440640b2031d47d331169ef39d477c01f851ad604038776f6461d723d2d7e5ed24140b2ddbd1b4617d1c0",
          "sha256": "51763e07abf28bda91d0ecd70cf18fa262168449a701e49e6b44b196b9020e34",
          "sha1": "03b923594d0d92ebedde2b9300a1c15eb38d0c16",
          "md5": "f5a63778e33d1140a0f1427151a27077"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "orbit-master-SNAPSHOT.aar",
          "url": "orbit-master-SNAPSHOT.aar",
          "size": 35803,
          "sha512": "e8e627bb131fefba999688fef3d7cf4c103fcc0a9ab440640b2031d47d331169ef39d477c01f851ad604038776f6461d723d2d7e5ed24140b2ddbd1b4617d1c0",
          "sha256": "51763e07abf28bda91d0ecd70cf18fa262168449a701e49e6b44b196b9020e34",
          "sha1": "03b923594d0d92ebedde2b9300a1c15eb38d0c16",
          "md5": "f5a63778e33d1140a0f1427151a27077"
        }
      ]
    }
  ]
}
