{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "colors",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "b3tfmloigvehbhz4a4ltgz2qey"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "colors-master-SNAPSHOT.aar",
          "url": "colors-master-SNAPSHOT.aar",
          "size": 9860,
          "sha512": "5c119b56aae94e08fde642c1be8eda861886d6ca5a2b5490a79e07786da649b638499e9aad581f74af92236a784d004022f04bcd28234107fa54f0e7cb89db6a",
          "sha256": "b6df7d5abf3145241a8510ef9f4cec6f52bfacc30064c4e20305ae99517eb821",
          "sha1": "20e5790f7afa73f6e8a9fee433c6cdcbb8ff7dd3",
          "md5": "0b9dff6f358f6a0735323bcca3234b07"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "colors-master-SNAPSHOT.aar",
          "url": "colors-master-SNAPSHOT.aar",
          "size": 9860,
          "sha512": "5c119b56aae94e08fde642c1be8eda861886d6ca5a2b5490a79e07786da649b638499e9aad581f74af92236a784d004022f04bcd28234107fa54f0e7cb89db6a",
          "sha256": "b6df7d5abf3145241a8510ef9f4cec6f52bfacc30064c4e20305ae99517eb821",
          "sha1": "20e5790f7afa73f6e8a9fee433c6cdcbb8ff7dd3",
          "md5": "0b9dff6f358f6a0735323bcca3234b07"
        }
      ]
    }
  ]
}
