{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "compass",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "kdn2zoz3afe7lk4r7unyaccymi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compass-master-SNAPSHOT.aar",
          "url": "compass-master-SNAPSHOT.aar",
          "size": 35541,
          "sha512": "8b812f4efd98f1fa26b6008f6262a10326bcfc4def671bc5f46cdf0a5064b4c6aba68047a376b5adb60e2192fd80922f0b0837540f473bb3ed3d4d38041f7012",
          "sha256": "58a490e04d0ca616412cd33033cee2ec16a3910c86b307f1c68fba548b6eb4e7",
          "sha1": "dd524ab12c74c29b7cdd6f8897fd2a4c43edb012",
          "md5": "66b46018f9a546744cca2ddd2b67edf8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "compass-master-SNAPSHOT.aar",
          "url": "compass-master-SNAPSHOT.aar",
          "size": 35541,
          "sha512": "8b812f4efd98f1fa26b6008f6262a10326bcfc4def671bc5f46cdf0a5064b4c6aba68047a376b5adb60e2192fd80922f0b0837540f473bb3ed3d4d38041f7012",
          "sha256": "58a490e04d0ca616412cd33033cee2ec16a3910c86b307f1c68fba548b6eb4e7",
          "sha1": "dd524ab12c74c29b7cdd6f8897fd2a4c43edb012",
          "md5": "66b46018f9a546744cca2ddd2b67edf8"
        }
      ]
    }
  ]
}
