{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "3n46gqbuvvga7dmi5q4ftpi7dy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25389,
          "sha512": "23b64401f56ff213987fbe68e1085e72362ee6c60e54d96aca57aa5d18ca9944422739485765aa665b3143a43db6af9a61b07788e7a876f4e185a5f7651f5c6d",
          "sha256": "37c7404565b2802881b3350cfa23ca3897bcb18edbc49c9435584618059ff922",
          "sha1": "d974fb6ff729141aaa4778d5d0aaa387f94acef4",
          "md5": "dfcaec0df37ca8ac41b7fe4e10f9cde1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25389,
          "sha512": "23b64401f56ff213987fbe68e1085e72362ee6c60e54d96aca57aa5d18ca9944422739485765aa665b3143a43db6af9a61b07788e7a876f4e185a5f7651f5c6d",
          "sha256": "37c7404565b2802881b3350cfa23ca3897bcb18edbc49c9435584618059ff922",
          "sha1": "d974fb6ff729141aaa4778d5d0aaa387f94acef4",
          "md5": "dfcaec0df37ca8ac41b7fe4e10f9cde1"
        }
      ]
    }
  ]
}
