{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "qkhi6nlaqvbgfizhe3npvj6jrm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25523,
          "sha512": "6617929800e8207c5d3b0dfc46afaa385a00707e1825fe5dfd33c55ef2d069916d01fbff5c67420cea69ed818dfe3a9a9df29eb756d65d4d5f604ddefcb8d076",
          "sha256": "25c7f1a300fb491ed0c037eeab94fb6b5ed832a7a6b6c61ade192b4e67299a1d",
          "sha1": "24296bcad318c83a782f4b30c5e357ed6d5d2893",
          "md5": "bbead9eb264bc2309ace413ec0f9c357"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25523,
          "sha512": "6617929800e8207c5d3b0dfc46afaa385a00707e1825fe5dfd33c55ef2d069916d01fbff5c67420cea69ed818dfe3a9a9df29eb756d65d4d5f604ddefcb8d076",
          "sha256": "25c7f1a300fb491ed0c037eeab94fb6b5ed832a7a6b6c61ade192b4e67299a1d",
          "sha1": "24296bcad318c83a782f4b30c5e357ed6d5d2893",
          "md5": "bbead9eb264bc2309ace413ec0f9c357"
        }
      ]
    }
  ]
}
