{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "l5bntddeovahld3cluahfqnqoa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25747,
          "sha512": "7e3415afee7ad8e5d7f9af54c9f92ee3bce37bd4a9dc6d0941f158fbb1e05c20ea94d3bf3aa810b580f05c534f6b8d1a894d680b283c4eb321fdc127ea37ff85",
          "sha256": "d094ccd2d7a62079b5bffb65471da2e3587375e3c4ba5f6610a913481f8765e9",
          "sha1": "0aae68a9afd0c5a6976ebb79cff23c4558b18c22",
          "md5": "994e01cc9cf8d53fecf340c856340f21"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-1.0.0.aar",
          "url": "dagger-viewmodel-1.0.0.aar",
          "size": 25747,
          "sha512": "7e3415afee7ad8e5d7f9af54c9f92ee3bce37bd4a9dc6d0941f158fbb1e05c20ea94d3bf3aa810b580f05c534f6b8d1a894d680b283c4eb321fdc127ea37ff85",
          "sha256": "d094ccd2d7a62079b5bffb65471da2e3587375e3c4ba5f6610a913481f8765e9",
          "sha1": "0aae68a9afd0c5a6976ebb79cff23c4558b18c22",
          "md5": "994e01cc9cf8d53fecf340c856340f21"
        }
      ]
    }
  ]
}
