{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "orbit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "3n46gqbuvvga7dmi5q4ftpi7dy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "orbit-1.0.0.aar",
          "url": "orbit-1.0.0.aar",
          "size": 35672,
          "sha512": "d135e8f3a3c20646e0d0119d85cd5846fb2a0a66af321999239e9b11aa8000739cf7fd7065b43d1564081fadce560c0f4ccefe06564a221e95ee0295bee52b94",
          "sha256": "d63b86cb70eab7daff018ba9da2dd2b7c5139132fbbab46dce77dd8a1500dd22",
          "sha1": "ece84d1ff0c03ead14fc7134ccf626533e04fc74",
          "md5": "91c034a79926814a759e0a459e548c2d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "orbit-1.0.0.aar",
          "url": "orbit-1.0.0.aar",
          "size": 35672,
          "sha512": "d135e8f3a3c20646e0d0119d85cd5846fb2a0a66af321999239e9b11aa8000739cf7fd7065b43d1564081fadce560c0f4ccefe06564a221e95ee0295bee52b94",
          "sha256": "d63b86cb70eab7daff018ba9da2dd2b7c5139132fbbab46dce77dd8a1500dd22",
          "sha1": "ece84d1ff0c03ead14fc7134ccf626533e04fc74",
          "md5": "91c034a79926814a759e0a459e548c2d"
        }
      ]
    }
  ]
}
