{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "oovmjdrtwze5tj25b7kme5wmlq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-1.0.0.aar",
          "url": "glide-component-icon-1.0.0.aar",
          "size": 11564,
          "sha512": "90d7687968349b1a84b11507f80409987a0a705b2c4e8b169097215345db914991cb34670b5147a872c6ddb6300854731023db95d500d82680f44f44d5e6d48e",
          "sha256": "c20fd880d01cdbfa61f7ab1ad917e3297c8370b8db830f883952839bdf65581c",
          "sha1": "a5fe375fd627879b6166e00af650f5ae5197c053",
          "md5": "5ff254001faccf0664104fadc4dccd6e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-1.0.0.aar",
          "url": "glide-component-icon-1.0.0.aar",
          "size": 11564,
          "sha512": "90d7687968349b1a84b11507f80409987a0a705b2c4e8b169097215345db914991cb34670b5147a872c6ddb6300854731023db95d500d82680f44f44d5e6d48e",
          "sha256": "c20fd880d01cdbfa61f7ab1ad917e3297c8370b8db830f883952839bdf65581c",
          "sha1": "a5fe375fd627879b6166e00af650f5ae5197c053",
          "md5": "5ff254001faccf0664104fadc4dccd6e"
        }
      ]
    }
  ]
}
