{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "oqvocydmkrbzpjpbm3omis5pza"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25795,
          "sha512": "83396e56425796ac622ee507f47757619ac8616c6bc7aa90a501c3d6a98e487d4318edb74bde425b61cd9477cced16e9a1fe276550053e1fcca8389cfa36f3de",
          "sha256": "2f7280169024eba94eb871a8700c5d8ed5a8a92a0aae6e4637b715a52c6f66ab",
          "sha1": "49dedfa8a8c7ec211d2231840133ad3e3c7149ef",
          "md5": "ba1fe2f54e749d1527dfc0b8a4952ef5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25795,
          "sha512": "83396e56425796ac622ee507f47757619ac8616c6bc7aa90a501c3d6a98e487d4318edb74bde425b61cd9477cced16e9a1fe276550053e1fcca8389cfa36f3de",
          "sha256": "2f7280169024eba94eb871a8700c5d8ed5a8a92a0aae6e4637b715a52c6f66ab",
          "sha1": "49dedfa8a8c7ec211d2231840133ad3e3c7149ef",
          "md5": "ba1fe2f54e749d1527dfc0b8a4952ef5"
        }
      ]
    }
  ]
}
