{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "bpzm7jo5vrberkyq7xrfdfsi3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-20200127.110247-2.aar",
          "size": 25380,
          "sha512": "dca8970364d38c4ade1f5909900c964110866069e6a7019e0f53d6fff29f900c6caf6fd4d93979c62af213c34172f227f68a3f573e3787eba2f0b6c5ac5cf51b",
          "sha256": "51f0a8ac53d7a9fe2db05032313c48bda52947ff0bf8540492b9d2db028e86fb",
          "sha1": "8d6f55c8a19f3edc629efb3c970d820d91437b9d",
          "md5": "43d9712eaefc666e8990ec3c73ff7a7a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-20200127.110247-2.aar",
          "size": 25380,
          "sha512": "dca8970364d38c4ade1f5909900c964110866069e6a7019e0f53d6fff29f900c6caf6fd4d93979c62af213c34172f227f68a3f573e3787eba2f0b6c5ac5cf51b",
          "sha256": "51f0a8ac53d7a9fe2db05032313c48bda52947ff0bf8540492b9d2db028e86fb",
          "sha1": "8d6f55c8a19f3edc629efb3c970d820d91437b9d",
          "md5": "43d9712eaefc666e8990ec3c73ff7a7a"
        }
      ]
    }
  ]
}
