{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ibtgjivkhfhx7apeermn6inv3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25875,
          "sha512": "42594fd7896b2f1c72d1ee02c0736e5f59f8a993574bdb28956375aae1c5a48b1aac1f30e52290db4ed714967ae6b7877d5058a7e6c445ad2db849dfefae4ee2",
          "sha256": "f49d6c4527587ab311171422d61453e31885f9ef4a07ad3460ef296f6175ffa5",
          "sha1": "9f24f03901139896ffa1f80ee5cd99e472771c1c",
          "md5": "ad537f209f174b274eec0c357d822d84"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25875,
          "sha512": "42594fd7896b2f1c72d1ee02c0736e5f59f8a993574bdb28956375aae1c5a48b1aac1f30e52290db4ed714967ae6b7877d5058a7e6c445ad2db849dfefae4ee2",
          "sha256": "f49d6c4527587ab311171422d61453e31885f9ef4a07ad3460ef296f6175ffa5",
          "sha1": "9f24f03901139896ffa1f80ee5cd99e472771c1c",
          "md5": "ad537f209f174b274eec0c357d822d84"
        }
      ]
    }
  ]
}
