{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-viewmodel",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "73ya3alxrbbt5mn6rk4noou2mu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25831,
          "sha512": "a395829f89642233c21f547b50dfcdc3f3505fe1c3e0a2ceec9fbbb93b60d4bcdcea69fbf7bf148230d839a357a9b323efdc114211233a1714bf4a2e3eb48fc4",
          "sha256": "a930622ff1613bfadbcd79d0e906997f779b91a243f65259572e74c7e65d99fc",
          "sha1": "77a9e591839b4834ec98f72df1eeb6e3db0f59cc",
          "md5": "d03dc8f17c26738c7104546b9bd1404e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-viewmodel-master-SNAPSHOT.aar",
          "url": "dagger-viewmodel-master-SNAPSHOT.aar",
          "size": 25831,
          "sha512": "a395829f89642233c21f547b50dfcdc3f3505fe1c3e0a2ceec9fbbb93b60d4bcdcea69fbf7bf148230d839a357a9b323efdc114211233a1714bf4a2e3eb48fc4",
          "sha256": "a930622ff1613bfadbcd79d0e906997f779b91a243f65259572e74c7e65d99fc",
          "sha1": "77a9e591839b4834ec98f72df1eeb6e3db0f59cc",
          "md5": "d03dc8f17c26738c7104546b9bd1404e"
        }
      ]
    }
  ]
}
