{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "bpzm7jo5vrberkyq7xrfdfsi3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-20200127.110247-2.aar",
          "size": 3798,
          "sha512": "c31373020f5fe20b633a07bdeaf4d19c8741a1584bf6c7cda23b3e2fb7de95cece160704cc6cbd7e0a3d8782bc90ed06bb79d0235bf0e48b3ef1f35fa0a8f485",
          "sha256": "c0c169770636983d08a52a2dc3198e8e387e48fc58151e6324b65637e1821e73",
          "sha1": "c1fb819858789e6e05b944cf552407f967085cf0",
          "md5": "65071837a6a96212ab2b1e5c26636241"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-20200127.110247-2.aar",
          "size": 3798,
          "sha512": "c31373020f5fe20b633a07bdeaf4d19c8741a1584bf6c7cda23b3e2fb7de95cece160704cc6cbd7e0a3d8782bc90ed06bb79d0235bf0e48b3ef1f35fa0a8f485",
          "sha256": "c0c169770636983d08a52a2dc3198e8e387e48fc58151e6324b65637e1821e73",
          "sha1": "c1fb819858789e6e05b944cf552407f967085cf0",
          "md5": "65071837a6a96212ab2b1e5c26636241"
        }
      ]
    }
  ]
}
