{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "yeswahorlzhrxp4q5tm57dyede"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3824,
          "sha512": "3d8e904d8d0e882406bf768eaa69472d1080d7d6f122b29253bfe165aaa46c1bb7780df0ec731e935b8aff6a33a870e13e1524fb7fac61799e09aaa1d3507f9f",
          "sha256": "8700a42d52455daa9e197b1ecfc31434b6dbcb26a6cb96cc76076a38a43bb841",
          "sha1": "0dc1bfe3a1e7328ea1dc56a1aac3613168961969",
          "md5": "4f722cdd32d299bfceeb4bfebe765f10"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3824,
          "sha512": "3d8e904d8d0e882406bf768eaa69472d1080d7d6f122b29253bfe165aaa46c1bb7780df0ec731e935b8aff6a33a870e13e1524fb7fac61799e09aaa1d3507f9f",
          "sha256": "8700a42d52455daa9e197b1ecfc31434b6dbcb26a6cb96cc76076a38a43bb841",
          "sha1": "0dc1bfe3a1e7328ea1dc56a1aac3613168961969",
          "md5": "4f722cdd32d299bfceeb4bfebe765f10"
        }
      ]
    }
  ]
}
