{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "rqbcbmp2gjg5zppjtjsvs37zuu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3815,
          "sha512": "dcf82f8fe8f48f137e65d5976831369b596769337efc83bb862734ff1c177ef4daf1220d93417ca10f8c53fc7f2013937dc44360d38f6817060df04ea7fb50f2",
          "sha256": "e810f1038acd224695280a798b2e42b48e01fdeab14569c14e3e4776ae99f422",
          "sha1": "32b1ac659cf4a9876df3f452f25f551f8e76a072",
          "md5": "c25761df3326a481e96d7084f4afbcb1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3815,
          "sha512": "dcf82f8fe8f48f137e65d5976831369b596769337efc83bb862734ff1c177ef4daf1220d93417ca10f8c53fc7f2013937dc44360d38f6817060df04ea7fb50f2",
          "sha256": "e810f1038acd224695280a798b2e42b48e01fdeab14569c14e3e4776ae99f422",
          "sha1": "32b1ac659cf4a9876df3f452f25f551f8e76a072",
          "md5": "c25761df3326a481e96d7084f4afbcb1"
        }
      ]
    }
  ]
}
