{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "a5uvm6i2erewro6aj65fk6ppsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-20200127.112201-3.aar",
          "size": 3787,
          "sha512": "d39c76d8db3f557630c43249fb68fa3b4a59c49f61d23967c62f845a5b894b01b8f899128e8613590ce2d536958669182067f9f90d557c7408705eec4d0ee150",
          "sha256": "9ed304f867810e3a3a27d9c700544b3a3e06725580524f45bf8f1eaf51530585",
          "sha1": "40cc9d24b2a7ce4376ca98b9c507e6e24cc67d86",
          "md5": "6ba3c9a4c18da0774b04467b7e73b218"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-20200127.112201-3.aar",
          "size": 3787,
          "sha512": "d39c76d8db3f557630c43249fb68fa3b4a59c49f61d23967c62f845a5b894b01b8f899128e8613590ce2d536958669182067f9f90d557c7408705eec4d0ee150",
          "sha256": "9ed304f867810e3a3a27d9c700544b3a3e06725580524f45bf8f1eaf51530585",
          "sha1": "40cc9d24b2a7ce4376ca98b9c507e6e24cc67d86",
          "md5": "6ba3c9a4c18da0774b04467b7e73b218"
        }
      ]
    }
  ]
}
