{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2qyg3riynbenzdtrablltx2xni"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3816,
          "sha512": "4fa87cff1f1e063007ed4e7513a84ec66f35726c4c3b2a1ac9c59d3db5685c90dced64196c895fbd39fcac6aeca50c407c53e10199c98f5a199978e8f16caf23",
          "sha256": "31c04c7deef84f3789a565baa28e4e4fe4c46f631b8efc95edc481b6eb55b128",
          "sha1": "dfcff2b48bbe97e5137eab74e31d0541638dc1b3",
          "md5": "a34c7c8daac250bc5d112b2a9e844e8b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-master-SNAPSHOT.aar",
          "url": "logging-master-SNAPSHOT.aar",
          "size": 3816,
          "sha512": "4fa87cff1f1e063007ed4e7513a84ec66f35726c4c3b2a1ac9c59d3db5685c90dced64196c895fbd39fcac6aeca50c407c53e10199c98f5a199978e8f16caf23",
          "sha256": "31c04c7deef84f3789a565baa28e4e4fe4c46f631b8efc95edc481b6eb55b128",
          "sha1": "dfcff2b48bbe97e5137eab74e31d0541638dc1b3",
          "md5": "a34c7c8daac250bc5d112b2a9e844e8b"
        }
      ]
    }
  ]
}
