{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "va6gft5fezfo7amkonmjursz5u"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7869,
          "sha512": "9843145c0244954b2b91bd38282780f2c451321961df7eb876ab6761f135560f42e5cb1666665fc771e0193fff181fc1442b525f960336441dbc1d510637ac47",
          "sha256": "1efe7c08a8300addad985be78202eb4e1171d4d8ce3183a50600227e18c46985",
          "sha1": "55fa861d6ad2ce9f51fd5786a11af453cda18cd4",
          "md5": "a0d4a4f995f545d87e95c51947782dfb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7869,
          "sha512": "9843145c0244954b2b91bd38282780f2c451321961df7eb876ab6761f135560f42e5cb1666665fc771e0193fff181fc1442b525f960336441dbc1d510637ac47",
          "sha256": "1efe7c08a8300addad985be78202eb4e1171d4d8ce3183a50600227e18c46985",
          "sha1": "55fa861d6ad2ce9f51fd5786a11af453cda18cd4",
          "md5": "a0d4a4f995f545d87e95c51947782dfb"
        }
      ]
    }
  ]
}
