{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "vamn7kmqhbcanmnkamshex4lae"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7859,
          "sha512": "d65506e16c3c0af3bf38b61f204ec3f39eda8c2c4d02d017e48a98d645a84937c7d9af2830653758ef9ac72849a9ade69fb4f933925338d6eed59d3a6ce736fd",
          "sha256": "4351c8542b17f6d82fa1b9f8570aa0e3a048204246d219cd592c65d4b20ff910",
          "sha1": "92b41a20dc68c82c9f851eadd1324cb77135aebe",
          "md5": "17536fd997db0c277ef7bc0260853170"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7859,
          "sha512": "d65506e16c3c0af3bf38b61f204ec3f39eda8c2c4d02d017e48a98d645a84937c7d9af2830653758ef9ac72849a9ade69fb4f933925338d6eed59d3a6ce736fd",
          "sha256": "4351c8542b17f6d82fa1b9f8570aa0e3a048204246d219cd592c65d4b20ff910",
          "sha1": "92b41a20dc68c82c9f851eadd1324cb77135aebe",
          "md5": "17536fd997db0c277ef7bc0260853170"
        }
      ]
    }
  ]
}
