{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "x3cp7rdjtndptc4l5m7eti34pu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7990,
          "sha512": "02ed476916f7e65629559c4d4c90a717feb9320ecba511cdb145247f4072ce5acb037d6392e7129d4097240188dba98df10d873980de678281cf6636fd5779f6",
          "sha256": "d6ef98a46a1d0bc66387bd6aa7a359b9a84169c4e05939a83f726fc62b9a472a",
          "sha1": "d9b8860b132ef702c57080091ce8157908cb1ffa",
          "md5": "7250481b52e1f0295e0ffd5c328c9d4b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-1.0.0.aar",
          "url": "viewmodel-utils-1.0.0.aar",
          "size": 7990,
          "sha512": "02ed476916f7e65629559c4d4c90a717feb9320ecba511cdb145247f4072ce5acb037d6392e7129d4097240188dba98df10d873980de678281cf6636fd5779f6",
          "sha256": "d6ef98a46a1d0bc66387bd6aa7a359b9a84169c4e05939a83f726fc62b9a472a",
          "sha1": "d9b8860b132ef702c57080091ce8157908cb1ffa",
          "md5": "7250481b52e1f0295e0ffd5c328c9d4b"
        }
      ]
    }
  ]
}
