{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "compass",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "jeoagc4sengdlj33ugwo423rja"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compass-1.0.0.aar",
          "url": "compass-1.0.0.aar",
          "size": 42992,
          "sha512": "cf666c6645a2f27ba932cadc39a27a3d052836cde77ac1ac2381445e49a76d0a0ff21ea2241ba02689e26aa6ce524495a0dbab7d21259e4a67eed3035898c30b",
          "sha256": "5056b970134e481a828be124039cbf8ec692a3973b7bfbdf78e5d0b559fd895d",
          "sha1": "3a2699cb783b294df8da5e4e05d35bb7131c3f06",
          "md5": "f31e7f8e73fe5073fcee59f00271cf35"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "compass-1.0.0.aar",
          "url": "compass-1.0.0.aar",
          "size": 42992,
          "sha512": "cf666c6645a2f27ba932cadc39a27a3d052836cde77ac1ac2381445e49a76d0a0ff21ea2241ba02689e26aa6ce524495a0dbab7d21259e4a67eed3035898c30b",
          "sha256": "5056b970134e481a828be124039cbf8ec692a3973b7bfbdf78e5d0b559fd895d",
          "sha1": "3a2699cb783b294df8da5e4e05d35bb7131c3f06",
          "md5": "f31e7f8e73fe5073fcee59f00271cf35"
        }
      ]
    }
  ]
}
