{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dt5lnliqerfrresoqrdnovhsda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-1.0.0.aar",
          "url": "epoxy-utils-1.0.0.aar",
          "size": 27507,
          "sha512": "f1ac17fe8c94e8802e4cd7ffe8a18980f37e8af933017abf52c63b7eec4286c608408a8df3b0d30e0524436c07bc7732a09de6b71cfb139422a91b92c462ecb6",
          "sha256": "a9487383c89bada9e103bcdbe7657c405025fd8fbdad9c525b36d6ba32d5fb59",
          "sha1": "5e0cea042a91825fb10defccb0390434c2f599ca",
          "md5": "a2694f457eb33fe66993145e3849ad49"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-1.0.0.aar",
          "url": "epoxy-utils-1.0.0.aar",
          "size": 27507,
          "sha512": "f1ac17fe8c94e8802e4cd7ffe8a18980f37e8af933017abf52c63b7eec4286c608408a8df3b0d30e0524436c07bc7732a09de6b71cfb139422a91b92c462ecb6",
          "sha256": "a9487383c89bada9e103bcdbe7657c405025fd8fbdad9c525b36d6ba32d5fb59",
          "sha1": "5e0cea042a91825fb10defccb0390434c2f599ca",
          "md5": "a2694f457eb33fe66993145e3849ad49"
        }
      ]
    }
  ]
}
