{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "preferences",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "b3tfmloigvehbhz4a4ltgz2qey"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-rx",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "rxjava",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "preferences-master-SNAPSHOT.aar",
          "url": "preferences-master-SNAPSHOT.aar",
          "size": 108108,
          "sha512": "8b49bd00c80f60665a221e03420c4c3067a415fffe6f9e41f4eac2ad78790b5c52542cd279af579e71a192663502f8d1751653be46d29074e437c8d74bc01b9a",
          "sha256": "c1bf3fcecf19465ac82b47bcd45200e32037dabbc44f95d846083c3c5137674a",
          "sha1": "2e9b730abc9529e05617d8c9f87d1425505a1709",
          "md5": "ca33c483f5b63437c867c76ec944991c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-rx",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "rxjava",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "preferences-master-SNAPSHOT.aar",
          "url": "preferences-master-SNAPSHOT.aar",
          "size": 108108,
          "sha512": "8b49bd00c80f60665a221e03420c4c3067a415fffe6f9e41f4eac2ad78790b5c52542cd279af579e71a192663502f8d1751653be46d29074e437c8d74bc01b9a",
          "sha256": "c1bf3fcecf19465ac82b47bcd45200e32037dabbc44f95d846083c3c5137674a",
          "sha1": "2e9b730abc9529e05617d8c9f87d1425505a1709",
          "md5": "ca33c483f5b63437c867c76ec944991c"
        }
      ]
    }
  ]
}
