{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "bqfb2pg33jchncbap375hsdj74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3917,
          "sha512": "7aef784ff0f9b344ce420263818ce7ddbc91ee21bb778646e4d8d06be24e27fdc81ada664633524bd9a39b8439e782988e4423db209fdcb1b2cfe9ac57c042a1",
          "sha256": "90701aea1c6d2e79f4b728d60ad8fdc3754a80b2903299b6fad3dba229a11ab1",
          "sha1": "4458e97532324dbd0199ad1406b9bd7895a1685b",
          "md5": "17431350840995909925679d7d1ca219"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3917,
          "sha512": "7aef784ff0f9b344ce420263818ce7ddbc91ee21bb778646e4d8d06be24e27fdc81ada664633524bd9a39b8439e782988e4423db209fdcb1b2cfe9ac57c042a1",
          "sha256": "90701aea1c6d2e79f4b728d60ad8fdc3754a80b2903299b6fad3dba229a11ab1",
          "sha1": "4458e97532324dbd0199ad1406b9bd7895a1685b",
          "md5": "17431350840995909925679d7d1ca219"
        }
      ]
    }
  ]
}
