{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ndukemifbrda5m6sfixbqobjfy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3833,
          "sha512": "31575f77fe9c8d3a508a4bbef6e0a9ce1511f9ab68d9f00bcffc69303aeac7d52daf1dca4c2582860ad0043c82ba4861f46a149fea23d68df910cf6def2a152f",
          "sha256": "0506075aba8aa675b8d8d5905e00cc209b7f1ccbaf3d2f35d29c35327feadc7b",
          "sha1": "0967480e04c79267108c728453d997e1d4cd03e0",
          "md5": "1388a2e311d6d6049ed817c01421bf64"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3833,
          "sha512": "31575f77fe9c8d3a508a4bbef6e0a9ce1511f9ab68d9f00bcffc69303aeac7d52daf1dca4c2582860ad0043c82ba4861f46a149fea23d68df910cf6def2a152f",
          "sha256": "0506075aba8aa675b8d8d5905e00cc209b7f1ccbaf3d2f35d29c35327feadc7b",
          "sha1": "0967480e04c79267108c728453d997e1d4cd03e0",
          "md5": "1388a2e311d6d6049ed817c01421bf64"
        }
      ]
    }
  ]
}
