{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "logging",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "mbkojahj55egljmcbdl7kftaea"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3807,
          "sha512": "e325910f080eefb2edbfb0d4b4d3401cde17097942d90524ab24a873414e0e3a65578435ba6799971fc24b00ad1db49416fe91ab09e9d967010b07d6db207125",
          "sha256": "42ec9f2681e5785fb205dad8a1c4d094c5a7587b07edb45ce66a750e2bdf2590",
          "sha1": "04668f1d23df9dac0a1388e08176779793b1c72c",
          "md5": "d7f352b700d1a11b089966c6ed3b24a6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0.aar",
          "url": "logging-1.0.0.aar",
          "size": 3807,
          "sha512": "e325910f080eefb2edbfb0d4b4d3401cde17097942d90524ab24a873414e0e3a65578435ba6799971fc24b00ad1db49416fe91ab09e9d967010b07d6db207125",
          "sha256": "42ec9f2681e5785fb205dad8a1c4d094c5a7587b07edb45ce66a750e2bdf2590",
          "sha1": "04668f1d23df9dac0a1388e08176779793b1c72c",
          "md5": "d7f352b700d1a11b089966c6ed3b24a6"
        }
      ]
    }
  ]
}
