{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "mbkojahj55egljmcbdl7kftaea"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-1.0.0.aar",
          "url": "rx-utils-1.0.0.aar",
          "size": 30683,
          "sha512": "838689e0e5272327b808febd946e2703dad66a4b9592a9c78a11a95bb5836162da6156113cebf9a91dfb5965b7e7460b38ef58700a053a0baa073ccfec1fb22f",
          "sha256": "d9f8b0b72fe9e9f1ff3245787bb633d0fdc230ab00992e879be7c4fa9f6c7c70",
          "sha1": "402f17f07f445285194b86343b3c459f71b6c833",
          "md5": "a93831a652126b69f8a82905789f1d0d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-1.0.0.aar",
          "url": "rx-utils-1.0.0.aar",
          "size": 30683,
          "sha512": "838689e0e5272327b808febd946e2703dad66a4b9592a9c78a11a95bb5836162da6156113cebf9a91dfb5965b7e7460b38ef58700a053a0baa073ccfec1fb22f",
          "sha256": "d9f8b0b72fe9e9f1ff3245787bb633d0fdc230ab00992e879be7c4fa9f6c7c70",
          "sha1": "402f17f07f445285194b86343b3c459f71b6c833",
          "md5": "a93831a652126b69f8a82905789f1d0d"
        }
      ]
    }
  ]
}
