{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3xysn66g7jd7djz4y43z2ovgeq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-1.0.0.aar",
          "url": "rx-utils-1.0.0.aar",
          "size": 35345,
          "sha512": "3d49049cedd96e2115067e0c1e2000230a47624fcb44e9581001d25e9d13bcb7c75429c2c75605b6c7d33edcf2b2e894926770a688956f9e90c5679705741047",
          "sha256": "bddd0f8552db162b51e4313707cf3376aece35bd2783e773f9b5598f2986b9a5",
          "sha1": "bac1a8750bf2232baffff46532f7e0b0d4844c2c",
          "md5": "92d9bf6e74847516a00e6782845934c1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-1.0.0.aar",
          "url": "rx-utils-1.0.0.aar",
          "size": 35345,
          "sha512": "3d49049cedd96e2115067e0c1e2000230a47624fcb44e9581001d25e9d13bcb7c75429c2c75605b6c7d33edcf2b2e894926770a688956f9e90c5679705741047",
          "sha256": "bddd0f8552db162b51e4313707cf3376aece35bd2783e773f9b5598f2986b9a5",
          "sha1": "bac1a8750bf2232baffff46532f7e0b0d4844c2c",
          "md5": "92d9bf6e74847516a00e6782845934c1"
        }
      ]
    }
  ]
}
