{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "73ya3alxrbbt5mn6rk4noou2mu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11648,
          "sha512": "f9d754910509c7f1ae1db2ce017aeb39dd73010b677ba7798c3bbdd7a5edf5711eb5091dd1c8a753bf460e7415422e16e5ca48fe2125ab2fb3a7601d2528d0e4",
          "sha256": "5561f111083a6a36f0a9f81d7a7bb2ca9b5715f63b2a4f12a53f15afa43b8b9f",
          "sha1": "b7b016939290e8e9724b25b1f61cd7710c3316fa",
          "md5": "9e5d34cfa4d67f902e26e19b9b34f975"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11648,
          "sha512": "f9d754910509c7f1ae1db2ce017aeb39dd73010b677ba7798c3bbdd7a5edf5711eb5091dd1c8a753bf460e7415422e16e5ca48fe2125ab2fb3a7601d2528d0e4",
          "sha256": "5561f111083a6a36f0a9f81d7a7bb2ca9b5715f63b2a4f12a53f15afa43b8b9f",
          "sha1": "b7b016939290e8e9724b25b1f61cd7710c3316fa",
          "md5": "9e5d34cfa4d67f902e26e19b9b34f975"
        }
      ]
    }
  ]
}
