{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "x4urdvryg5a3dcvbesv3s7rvnq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-20200310.201649-1.aar",
          "size": 11643,
          "sha512": "24f89ed7ba0fbdbaabeb80700a5398e7c20e897d0b9e821d793c3afdd3edcb6f3473f4927fdbd040bba96029b8f13b9f686d851afc02edf301bdb302085f9f3d",
          "sha256": "bc36b2387f13eafdfd2adf78868bbe883286c2eb1db4b6b2cb51cb0dbd0e64fd",
          "sha1": "ab7e7e3f0519e967cc15dbbf32ba38675866b4f6",
          "md5": "e95e41c62de50fd1bc803878753d8a6d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-20200310.201649-1.aar",
          "size": 11643,
          "sha512": "24f89ed7ba0fbdbaabeb80700a5398e7c20e897d0b9e821d793c3afdd3edcb6f3473f4927fdbd040bba96029b8f13b9f686d851afc02edf301bdb302085f9f3d",
          "sha256": "bc36b2387f13eafdfd2adf78868bbe883286c2eb1db4b6b2cb51cb0dbd0e64fd",
          "sha1": "ab7e7e3f0519e967cc15dbbf32ba38675866b4f6",
          "md5": "e95e41c62de50fd1bc803878753d8a6d"
        }
      ]
    }
  ]
}
