{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "cdgwnd2zs5dyponlui6hh7mobm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11575,
          "sha512": "69482abce9c703d47ef1f259bde93ae0684ef1908495164bb0b70cd26a5610be6a62a3fe8bc09eaba8ce286723060d1ce1740a1dd3a9f193f9a6f258f04d0ccd",
          "sha256": "a6c21aabc67485597e817f0c0bd2f9fdd873e5eb56a949371ea4ee4e99d49459",
          "sha1": "08c4daf573704c14a09cd29b716feb91d52660cb",
          "md5": "8f833738260586dc50f3a406eea6dfc4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11575,
          "sha512": "69482abce9c703d47ef1f259bde93ae0684ef1908495164bb0b70cd26a5610be6a62a3fe8bc09eaba8ce286723060d1ce1740a1dd3a9f193f9a6f258f04d0ccd",
          "sha256": "a6c21aabc67485597e817f0c0bd2f9fdd873e5eb56a949371ea4ee4e99d49459",
          "sha1": "08c4daf573704c14a09cd29b716feb91d52660cb",
          "md5": "8f833738260586dc50f3a406eea6dfc4"
        }
      ]
    }
  ]
}
