{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "dklignzjincgpk54yjmfetzxfq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11558,
          "sha512": "8b2861e20a3e944dfa0b73d4c72d8b94917225bd3b40ff26d9a70bba3843b2cc6e722f7eaeb2beda68c51cc7ec9c337c91ecf0bbcea1f1d8f788141231c7519a",
          "sha256": "bf61edb28cc2a2ba52d3feb495f4870aae413f6f0d0664ba06e537851f9ad476",
          "sha1": "2179499c15044c131185a6e9638fb10091cef675",
          "md5": "1a6fd1095d4ea5cbfc09ad5e827c951a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11558,
          "sha512": "8b2861e20a3e944dfa0b73d4c72d8b94917225bd3b40ff26d9a70bba3843b2cc6e722f7eaeb2beda68c51cc7ec9c337c91ecf0bbcea1f1d8f788141231c7519a",
          "sha256": "bf61edb28cc2a2ba52d3feb495f4870aae413f6f0d0664ba06e537851f9ad476",
          "sha1": "2179499c15044c131185a6e9638fb10091cef675",
          "md5": "1a6fd1095d4ea5cbfc09ad5e827c951a"
        }
      ]
    }
  ]
}
