{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "glide-component-icon",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "cxe7s4idarapzhb2yi53zdkwiy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11564,
          "sha512": "8d747739cf96388d23a699e6cbf0fa3e7c59940637ca06f613fafacec315da585ee7f969dda34ddbf00a52c2a9ffd9024dccabf03d5c2d41c411543725ff4daa",
          "sha256": "090236b8662fae5fc074c8038649eda986b396991a898e0899c478f12700b09b",
          "sha1": "4baaedd94bcec69ecc600d463d2f1fc518c18139",
          "md5": "c5d3fda46c6b6e3ed4355c5b33c9bcef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "glide-component-icon-master-SNAPSHOT.aar",
          "url": "glide-component-icon-master-SNAPSHOT.aar",
          "size": 11564,
          "sha512": "8d747739cf96388d23a699e6cbf0fa3e7c59940637ca06f613fafacec315da585ee7f969dda34ddbf00a52c2a9ffd9024dccabf03d5c2d41c411543725ff4daa",
          "sha256": "090236b8662fae5fc074c8038649eda986b396991a898e0899c478f12700b09b",
          "sha1": "4baaedd94bcec69ecc600d463d2f1fc518c18139",
          "md5": "c5d3fda46c6b6e3ed4355c5b33c9bcef"
        }
      ]
    }
  ]
}
