{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-rx",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vy36zycys5ao3orvfxkzo2an64"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-master-SNAPSHOT.aar",
          "url": "epoxy-rx-master-SNAPSHOT.aar",
          "size": 33551,
          "sha512": "71165db9495af2fd646bcb00ccb1ba0b8322ee07284a5b7e13eb343a66d262a04eae077d8d0508994c12055dff1ffa75a1c71653f578072a774e1d476fcc13b5",
          "sha256": "4df2cf2cefbc2b727ad7c356ef4db9a0dddf84be3baf04e7c75d45ba9e3249fd",
          "sha1": "7ac67450d9b1dd42f7552d503d973ebd9f31cdf1",
          "md5": "6008896f6cd11bfa3359ca7ec3ebcd0d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-master-SNAPSHOT.aar",
          "url": "epoxy-rx-master-SNAPSHOT.aar",
          "size": 33551,
          "sha512": "71165db9495af2fd646bcb00ccb1ba0b8322ee07284a5b7e13eb343a66d262a04eae077d8d0508994c12055dff1ffa75a1c71653f578072a774e1d476fcc13b5",
          "sha256": "4df2cf2cefbc2b727ad7c356ef4db9a0dddf84be3baf04e7c75d45ba9e3249fd",
          "sha1": "7ac67450d9b1dd42f7552d503d973ebd9f31cdf1",
          "md5": "6008896f6cd11bfa3359ca7ec3ebcd0d"
        }
      ]
    }
  ]
}
