{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-rx",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "pw7jfks2bjboffjnwkemi4zrka"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-master-SNAPSHOT.aar",
          "url": "epoxy-rx-master-SNAPSHOT.aar",
          "size": 33543,
          "sha512": "b17b01cb2917d64ce4f49c608bf7a67827d0a6ae913c1099813476a54ffe03e0d25df66fe9b597023a8743d7778b6d57cdff207cce63fd49f0aabd6a31008850",
          "sha256": "c70bc6c488f1ec566aa30f4df24e6e52ddefff48909a717df9e881c25c664aba",
          "sha1": "0a2c94e78018825dd0b778c35fdb8cfaa062de26",
          "md5": "172a0de4f187e2e771b92e36bac68758"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "rx-utils",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-rx-master-SNAPSHOT.aar",
          "url": "epoxy-rx-master-SNAPSHOT.aar",
          "size": 33543,
          "sha512": "b17b01cb2917d64ce4f49c608bf7a67827d0a6ae913c1099813476a54ffe03e0d25df66fe9b597023a8743d7778b6d57cdff207cce63fd49f0aabd6a31008850",
          "sha256": "c70bc6c488f1ec566aa30f4df24e6e52ddefff48909a717df9e881c25c664aba",
          "sha1": "0a2c94e78018825dd0b778c35fdb8cfaa062de26",
          "md5": "172a0de4f187e2e771b92e36bac68758"
        }
      ]
    }
  ]
}
