{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "73ya3alxrbbt5mn6rk4noou2mu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7926,
          "sha512": "42a840b60b6a5edd5dd4c06d81477939ad642eeb517f843221ed9d439dace362095ccc9c0909457a721ef815afa0e55af58c1999eaa773b288133cfc45ebd47c",
          "sha256": "57e95f2ad1b76eee68be8c4b0bddd979d0ed37cbeb5fcde3c357a714ec9482b5",
          "sha1": "01182dce69ca5491db130f9516fd2365cb621cd6",
          "md5": "abea3052389b15158bfec32e4e676d97"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7926,
          "sha512": "42a840b60b6a5edd5dd4c06d81477939ad642eeb517f843221ed9d439dace362095ccc9c0909457a721ef815afa0e55af58c1999eaa773b288133cfc45ebd47c",
          "sha256": "57e95f2ad1b76eee68be8c4b0bddd979d0ed37cbeb5fcde3c357a714ec9482b5",
          "sha1": "01182dce69ca5491db130f9516fd2365cb621cd6",
          "md5": "abea3052389b15158bfec32e4e676d97"
        }
      ]
    }
  ]
}
