{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "a5uvm6i2erewro6aj65fk6ppsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-20200127.112201-3.aar",
          "size": 7921,
          "sha512": "375000f501bace3435fcfb83eae5bc1df5547e52708ff80ef0bf906091675b09afe26285c9f339c1bc0a4e64929794d3f6312fdb4e60ad8a7624c09e563e5cbf",
          "sha256": "d218bf4bb3d3b32bfa37936fb6ee23fd2b3a9e56ee2de4db6ba698593648f954",
          "sha1": "3060b0c764c047173bbeb852f9279446b31bda33",
          "md5": "2f29220e72b5a8d3d4e69cfb5f9a6d2e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-20200127.112201-3.aar",
          "size": 7921,
          "sha512": "375000f501bace3435fcfb83eae5bc1df5547e52708ff80ef0bf906091675b09afe26285c9f339c1bc0a4e64929794d3f6312fdb4e60ad8a7624c09e563e5cbf",
          "sha256": "d218bf4bb3d3b32bfa37936fb6ee23fd2b3a9e56ee2de4db6ba698593648f954",
          "sha1": "3060b0c764c047173bbeb852f9279446b31bda33",
          "md5": "2f29220e72b5a8d3d4e69cfb5f9a6d2e"
        }
      ]
    }
  ]
}
