{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2qyg3riynbenzdtrablltx2xni"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7922,
          "sha512": "67cb7d158b10ac8a58e323f42090d70160c018d61f99e11127b0d496fa7cc536ef711cbf15ae627055a74fa031e84879932bc4af175fc185c973f1cda390de60",
          "sha256": "962092bcdf62e6682dcf0bb011d97595293e2437f480684c02c4d23dd7dc5581",
          "sha1": "8f187115d4e29a98de605cb230b984d87de55cb9",
          "md5": "6e8f3866bfcad38362b63ee08b8724cb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7922,
          "sha512": "67cb7d158b10ac8a58e323f42090d70160c018d61f99e11127b0d496fa7cc536ef711cbf15ae627055a74fa031e84879932bc4af175fc185c973f1cda390de60",
          "sha256": "962092bcdf62e6682dcf0bb011d97595293e2437f480684c02c4d23dd7dc5581",
          "sha1": "8f187115d4e29a98de605cb230b984d87de55cb9",
          "md5": "6e8f3866bfcad38362b63ee08b8724cb"
        }
      ]
    }
  ]
}
