{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "viewmodel-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "h2ngcnj3ovhsreq22de4icynjq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7858,
          "sha512": "385c291b6804f9cd4d1112ef7db358a3e701fcb55dafed51ec647f5b7bb8991d9301ff46b566989a1479d5bdbf34da531b7055a4393fe33d0c28a729dfe78f46",
          "sha256": "e216eb71538b784b97f3618644af82feb00a7d03d5c825ef338b7555769706fe",
          "sha1": "a6f96215deb18836577cfa50c031a7d8a92f4310",
          "md5": "8831c6a2cb77b37fd4a66e19222d28b6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "com.jakewharton.rxrelay2",
          "module": "rxrelay",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-utils-master-SNAPSHOT.aar",
          "url": "viewmodel-utils-master-SNAPSHOT.aar",
          "size": 7858,
          "sha512": "385c291b6804f9cd4d1112ef7db358a3e701fcb55dafed51ec647f5b7bb8991d9301ff46b566989a1479d5bdbf34da531b7055a4393fe33d0c28a729dfe78f46",
          "sha256": "e216eb71538b784b97f3618644af82feb00a7d03d5c825ef338b7555769706fe",
          "sha1": "a6f96215deb18836577cfa50c031a7d8a92f4310",
          "md5": "8831c6a2cb77b37fd4a66e19222d28b6"
        }
      ]
    }
  ]
}
