{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ce43cls6vvfi5lmnuqjufuwv5a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 33962,
          "sha512": "5c7a6cd11cc9ec9dbdd70b650711a937a519a322ee6a8b16ad42071c2fe0d18b39ea07b9fe4111c0179cdcb8cc9d4b3f0cd0216e5d54e388ce580b3b2c5df725",
          "sha256": "9dcb8f7ef64b8f3b64042600ce1eb586b387b426d1aeed16ff41a75fd935219d",
          "sha1": "aa8aacb36e9b215061384d8b39aa2bddfad0625d",
          "md5": "fb3df94d57247466ce573a7ef7342474"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 33962,
          "sha512": "5c7a6cd11cc9ec9dbdd70b650711a937a519a322ee6a8b16ad42071c2fe0d18b39ea07b9fe4111c0179cdcb8cc9d4b3f0cd0216e5d54e388ce580b3b2c5df725",
          "sha256": "9dcb8f7ef64b8f3b64042600ce1eb586b387b426d1aeed16ff41a75fd935219d",
          "sha1": "aa8aacb36e9b215061384d8b39aa2bddfad0625d",
          "md5": "fb3df94d57247466ce573a7ef7342474"
        }
      ]
    }
  ]
}
