{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ibtgjivkhfhx7apeermn6inv3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 36703,
          "sha512": "4ddcdfb63b6db75a05bc3c4016269e4a4d3a69a60784cf190cbb8d43f588079b103f7c322e67169816ab327b4c4a1d236be8c68288c68f5bf0d78fb1467616a5",
          "sha256": "0d3cc6d4da4491ef7c18a5289221827be07ed6e8c95094f8046a1435d0ab9392",
          "sha1": "1462148dec1467d15a329b3ac320f704123f1c86",
          "md5": "2ae44038abbd5265c9ec87761e0caeb7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 36703,
          "sha512": "4ddcdfb63b6db75a05bc3c4016269e4a4d3a69a60784cf190cbb8d43f588079b103f7c322e67169816ab327b4c4a1d236be8c68288c68f5bf0d78fb1467616a5",
          "sha256": "0d3cc6d4da4491ef7c18a5289221827be07ed6e8c95094f8046a1435d0ab9392",
          "sha1": "1462148dec1467d15a329b3ac320f704123f1c86",
          "md5": "2ae44038abbd5265c9ec87761e0caeb7"
        }
      ]
    }
  ]
}
