{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5zsrm4crxzb6nijeqvms7qbqbq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 30951,
          "sha512": "fc73f81395b486f7e2ca3db698f96837dffb1941eaf81440d15148633b48bd185091b9fd0532d806e7dcf3527bcd3e98f90e75d3279f17cdb949905cb8b6b19f",
          "sha256": "1c96b9da61736b8570bc066c4c8fa7d9c5cb9aaabd3a1ded6ec6b0c3c7571df4",
          "sha1": "eb4c00c227a3278432bb4ffa8879252b35452c87",
          "md5": "13a519264a807153e9aa806f18ba01b2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 30951,
          "sha512": "fc73f81395b486f7e2ca3db698f96837dffb1941eaf81440d15148633b48bd185091b9fd0532d806e7dcf3527bcd3e98f90e75d3279f17cdb949905cb8b6b19f",
          "sha256": "1c96b9da61736b8570bc066c4c8fa7d9c5cb9aaabd3a1ded6ec6b0c3c7571df4",
          "sha1": "eb4c00c227a3278432bb4ffa8879252b35452c87",
          "md5": "13a519264a807153e9aa806f18ba01b2"
        }
      ]
    }
  ]
}
