{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "rx-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wogswejljzc4pge5rgydwprivi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 31699,
          "sha512": "799c39344b2d6d18b848554f55f2ea5b07ba627ecb3639022a470fa02899d5bf85e245260bec960b983d2d6f50a67ed6ecdbfcc1afbe4a0672779bf51d63347e",
          "sha256": "4b2fc869ffdcc17b19ebf16c3f1b3566cafb30fa1215222d5970b065c0baaa5f",
          "sha1": "9b499a61bc68f3534ef4a74829dfc19e4c7f98a3",
          "md5": "6b2d5d85ca3a8cc0c68909f33632b501"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-appcompat-v7-kotlin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "rx-utils-master-SNAPSHOT.aar",
          "url": "rx-utils-master-SNAPSHOT.aar",
          "size": 31699,
          "sha512": "799c39344b2d6d18b848554f55f2ea5b07ba627ecb3639022a470fa02899d5bf85e245260bec960b983d2d6f50a67ed6ecdbfcc1afbe4a0672779bf51d63347e",
          "sha256": "4b2fc869ffdcc17b19ebf16c3f1b3566cafb30fa1215222d5970b065c0baaa5f",
          "sha1": "9b499a61bc68f3534ef4a74829dfc19e4c7f98a3",
          "md5": "6b2d5d85ca3a8cc0c68909f33632b501"
        }
      ]
    }
  ]
}
