{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "5zsrm4crxzb6nijeqvms7qbqbq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 26043,
          "sha512": "5f6d6a79c15a457bfe6270ca9e70b35e761077042c80af522a53906ce75dabea1b332011da9c623085017a70fd88fa74fe0421a794c6a34b30c3ce39d2a696e1",
          "sha256": "edfd2a37ecad62ac7775dce434557e4775eb37f389379abfb44b4d4fb67b1044",
          "sha1": "f988aeba2b2cca95ac0541e208094b3cfed0eb45",
          "md5": "4b76f782ef636415e113a753a6dd0668"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 26043,
          "sha512": "5f6d6a79c15a457bfe6270ca9e70b35e761077042c80af522a53906ce75dabea1b332011da9c623085017a70fd88fa74fe0421a794c6a34b30c3ce39d2a696e1",
          "sha256": "edfd2a37ecad62ac7775dce434557e4775eb37f389379abfb44b4d4fb67b1044",
          "sha1": "f988aeba2b2cca95ac0541e208094b3cfed0eb45",
          "md5": "4b76f782ef636415e113a753a6dd0668"
        }
      ]
    }
  ]
}
