{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "cxe7s4idarapzhb2yi53zdkwiy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 24357,
          "sha512": "27ded7701966db1afa79b4aa165a87d5e0978cda377cb3ab7247cc22c8e6e1d4cf73b0f8fe181f9427323e29904ed5e3cd5d4d8920d03e2da684e971cef5914e",
          "sha256": "ae5edb4cff2df5b04a78a16ea590f0a5712cc17fd140501c5729263a66988ef8",
          "sha1": "702cfce2c0ba4ccbaa80b405c47cf128a46e6f63",
          "md5": "5ec537df093de8bfe444a171b9acb57c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 24357,
          "sha512": "27ded7701966db1afa79b4aa165a87d5e0978cda377cb3ab7247cc22c8e6e1d4cf73b0f8fe181f9427323e29904ed5e3cd5d4d8920d03e2da684e971cef5914e",
          "sha256": "ae5edb4cff2df5b04a78a16ea590f0a5712cc17fd140501c5729263a66988ef8",
          "sha1": "702cfce2c0ba4ccbaa80b405c47cf128a46e6f63",
          "md5": "5ec537df093de8bfe444a171b9acb57c"
        }
      ]
    }
  ]
}
