{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "bpzm7jo5vrberkyq7xrfdfsi3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-20200127.110247-2.aar",
          "size": 24288,
          "sha512": "8fe9b78ebc50375624d3e4d4142f8ec172f955dc3e7f1e86f2fe2f51868f868d3f0edea4c7717bbf17805fdcd103fd416d2d735102c14182266eeab76fba6bf8",
          "sha256": "d6884515c0cd277d08cc5c3b8380003cf2b0c9bcce3d0cc67edb699b348de1fe",
          "sha1": "4f96e4b989bfc6815f61c59b8881e609befe7acf",
          "md5": "142c2f8270d2c8890a5542854b4b0314"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-20200127.110247-2.aar",
          "size": 24288,
          "sha512": "8fe9b78ebc50375624d3e4d4142f8ec172f955dc3e7f1e86f2fe2f51868f868d3f0edea4c7717bbf17805fdcd103fd416d2d735102c14182266eeab76fba6bf8",
          "sha256": "d6884515c0cd277d08cc5c3b8380003cf2b0c9bcce3d0cc67edb699b348de1fe",
          "sha1": "4f96e4b989bfc6815f61c59b8881e609befe7acf",
          "md5": "142c2f8270d2c8890a5542854b4b0314"
        }
      ]
    }
  ]
}
