{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "h2ngcnj3ovhsreq22de4icynjq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 26042,
          "sha512": "5c10831b9615c2327c16082665bc5ecd413cf29429d9ae2f6d1d5544d3a4a4ad47c95bfb5a7b837d604b5d9320000a18a9727e390178f675ca8c7b89fcefcf7a",
          "sha256": "ca80b4b23b705924efadd8ad8104ea2fee722b343c58b4884969928a8e8eba75",
          "sha1": "43ae26d7fd683bcb60964fea6f909f56493d2c5d",
          "md5": "d648a13120b6b8700a5885ab01de3282"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 26042,
          "sha512": "5c10831b9615c2327c16082665bc5ecd413cf29429d9ae2f6d1d5544d3a4a4ad47c95bfb5a7b837d604b5d9320000a18a9727e390178f675ca8c7b89fcefcf7a",
          "sha256": "ca80b4b23b705924efadd8ad8104ea2fee722b343c58b4884969928a8e8eba75",
          "sha1": "43ae26d7fd683bcb60964fea6f909f56493d2c5d",
          "md5": "d648a13120b6b8700a5885ab01de3282"
        }
      ]
    }
  ]
}
