{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "epoxy-utils",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "b3tfmloigvehbhz4a4ltgz2qey"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 27425,
          "sha512": "67289643002d1ca9ff416e92c2c25fb9904513f98bb87ce62ac57e84ae86224abefb80a9ac9383bb83b24d031a088e854f63a0e6d44f0c2694ee2960e92aa53a",
          "sha256": "9d34d37cc8e25be4b7a0e8e89166c51396d570080272a1d758d07f405b901041",
          "sha1": "4b029b226987ddf3b9cf288b590394dc72acd10b",
          "md5": "0ba4e1ba4566abd693b21425b6d632a2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "epoxy-utils-master-SNAPSHOT.aar",
          "url": "epoxy-utils-master-SNAPSHOT.aar",
          "size": 27425,
          "sha512": "67289643002d1ca9ff416e92c2c25fb9904513f98bb87ce62ac57e84ae86224abefb80a9ac9383bb83b24d031a088e854f63a0e6d44f0c2694ee2960e92aa53a",
          "sha256": "9d34d37cc8e25be4b7a0e8e89166c51396d570080272a1d758d07f405b901041",
          "sha1": "4b029b226987ddf3b9cf288b590394dc72acd10b",
          "md5": "0ba4e1ba4566abd693b21425b6d632a2"
        }
      ]
    }
  ]
}
