{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wogswejljzc4pge5rgydwprivi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27578,
          "sha512": "02eff7dab33dbc3c54d7aef552894a60abf7e7446a0f4b0f8598b5afcacd49654e332cb62f3ae9594b6298de20daee07cf16a5b79f652696848e1e153f5ef3c9",
          "sha256": "b54c93d99b6e900f6c5f21b568056bfd45faf862aa46930bcc48ceb538945498",
          "sha1": "5a0098b38efefec3ce5119e10e64c767fc70ce19",
          "md5": "204fa109ffd0f1aeda064248f6328384"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27578,
          "sha512": "02eff7dab33dbc3c54d7aef552894a60abf7e7446a0f4b0f8598b5afcacd49654e332cb62f3ae9594b6298de20daee07cf16a5b79f652696848e1e153f5ef3c9",
          "sha256": "b54c93d99b6e900f6c5f21b568056bfd45faf862aa46930bcc48ceb538945498",
          "sha1": "5a0098b38efefec3ce5119e10e64c767fc70ce19",
          "md5": "204fa109ffd0f1aeda064248f6328384"
        }
      ]
    }
  ]
}
