{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "yeswahorlzhrxp4q5tm57dyede"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27591,
          "sha512": "4cc902d22483ebc74593b37d4d576e3c7d63721d726f89f25a9b3ca63b9fd17084f1ab88f7bb1f12775ee6a36ea0964784bb12418819d9705d7e678f7c30ba4c",
          "sha256": "0ebdc1b582e58f82bffeacb891bfe476cf600de8a5d6f0ab87b6014145fa1933",
          "sha1": "83c9ba883bb72c59012b1f496a8c0d509b52d959",
          "md5": "d76fa35c2074a27356b061f6c0a0dfac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27591,
          "sha512": "4cc902d22483ebc74593b37d4d576e3c7d63721d726f89f25a9b3ca63b9fd17084f1ab88f7bb1f12775ee6a36ea0964784bb12418819d9705d7e678f7c30ba4c",
          "sha256": "0ebdc1b582e58f82bffeacb891bfe476cf600de8a5d6f0ab87b6014145fa1933",
          "sha1": "83c9ba883bb72c59012b1f496a8c0d509b52d959",
          "md5": "d76fa35c2074a27356b061f6c0a0dfac"
        }
      ]
    }
  ]
}
