{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "rqbcbmp2gjg5zppjtjsvs37zuu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27580,
          "sha512": "459009f3e9232c8f0e3e347526b20a75420cc4526d3b1cdd3dd419a547cd7161ca19dd5f28ddd32a95a6d13e6eee4d9665adcff2999b6b160a083fcbd96ee898",
          "sha256": "a52b6596e86c4649023ce270f4a0baea05a6d9961aad4decce8bec544b10722c",
          "sha1": "3c93390fe79ec9664e98415f67dca784ef7698c0",
          "md5": "f2dfda9f79658b2bc7797448f155d368"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27580,
          "sha512": "459009f3e9232c8f0e3e347526b20a75420cc4526d3b1cdd3dd419a547cd7161ca19dd5f28ddd32a95a6d13e6eee4d9665adcff2999b6b160a083fcbd96ee898",
          "sha256": "a52b6596e86c4649023ce270f4a0baea05a6d9961aad4decce8bec544b10722c",
          "sha1": "3c93390fe79ec9664e98415f67dca784ef7698c0",
          "md5": "f2dfda9f79658b2bc7797448f155d368"
        }
      ]
    }
  ]
}
