{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6f75z5moonfrhd6boderjwsvzu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27589,
          "sha512": "a481ddd37b24c1660f908c159374c2f09ed24face00313902aace2301f586892bdcdd7f7a495dfc09cb07e3a0708c6e0f6759cb8129f28a6875d981bdfdcdde8",
          "sha256": "032a42a33aa6d16659f95accc27676e17f3d622a558fe04c08b3e6847bc5769c",
          "sha1": "caf17864d6c77db567cc7b105cdc9a9c583f20ea",
          "md5": "74540e8481a285df51b72c74be3dbfef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27589,
          "sha512": "a481ddd37b24c1660f908c159374c2f09ed24face00313902aace2301f586892bdcdd7f7a495dfc09cb07e3a0708c6e0f6759cb8129f28a6875d981bdfdcdde8",
          "sha256": "032a42a33aa6d16659f95accc27676e17f3d622a558fe04c08b3e6847bc5769c",
          "sha1": "caf17864d6c77db567cc7b105cdc9a9c583f20ea",
          "md5": "74540e8481a285df51b72c74be3dbfef"
        }
      ]
    }
  ]
}
