{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "bpzm7jo5vrberkyq7xrfdfsi3e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-20200127.110247-2.aar",
          "size": 24856,
          "sha512": "aeeb5f94dabf31c7b4355f4d6db474eabf44af463ad3332d348078f3489f9ba8a49da8f812eea4315c264e3e53ef0aca31ee79196ff17553848008c0120c6a3d",
          "sha256": "1528836baee292bbcd397f59bd3c3d11bc136cc3a19303e3b2ec9b5d3edd4741",
          "sha1": "552fb6f4667e6bbc9b9da4464a26f4761de37bff",
          "md5": "467023beeaad964604edc84067e348bb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-20200127.110247-2.aar",
          "size": 24856,
          "sha512": "aeeb5f94dabf31c7b4355f4d6db474eabf44af463ad3332d348078f3489f9ba8a49da8f812eea4315c264e3e53ef0aca31ee79196ff17553848008c0120c6a3d",
          "sha256": "1528836baee292bbcd397f59bd3c3d11bc136cc3a19303e3b2ec9b5d3edd4741",
          "sha1": "552fb6f4667e6bbc9b9da4464a26f4761de37bff",
          "md5": "467023beeaad964604edc84067e348bb"
        }
      ]
    }
  ]
}
