{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "lzvivyt2fzgn7d2tllggsgdija"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27962,
          "sha512": "11dbc1ec23d802cee7a5e3f0aa0e2c6dc14af475d4d3c95e320b01e95d9ec864fe4aaf5f33e2fd26f062c12772d2087bcdfcb915fa1186488d468023f4909918",
          "sha256": "e5797d5494390482acade513b062aa93c67ebeded20eae8e9aef1d9616c3f43b",
          "sha1": "11e1c8ea4eabb7cad0c53b54d1a554bddbda2987",
          "md5": "4ae330ca451c70a05944ba22e095d962"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 27962,
          "sha512": "11dbc1ec23d802cee7a5e3f0aa0e2c6dc14af475d4d3c95e320b01e95d9ec864fe4aaf5f33e2fd26f062c12772d2087bcdfcb915fa1186488d468023f4909918",
          "sha256": "e5797d5494390482acade513b062aa93c67ebeded20eae8e9aef1d9616c3f43b",
          "sha1": "11e1c8ea4eabb7cad0c53b54d1a554bddbda2987",
          "md5": "4ae330ca451c70a05944ba22e095d962"
        }
      ]
    }
  ]
}
