{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ce43cls6vvfi5lmnuqjufuwv5a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 28814,
          "sha512": "c9fd08814d5837f4906b5e168f9cdaf4edf4502a21453d1f61b7324db2dea81f3d0b6135e1fb484ada8154db9d651632e880daf9457992c971f3dd42492af88b",
          "sha256": "e5add3cee2ac57abc0ee81e03662fa7f26b34ed82dc82d8dfeba569fb15e087a",
          "sha1": "b60b9160d544ed02881aa214c139d611a0196d8b",
          "md5": "531a0c17d84a001157ee32e5fd34c7b3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 28814,
          "sha512": "c9fd08814d5837f4906b5e168f9cdaf4edf4502a21453d1f61b7324db2dea81f3d0b6135e1fb484ada8154db9d651632e880daf9457992c971f3dd42492af88b",
          "sha256": "e5add3cee2ac57abc0ee81e03662fa7f26b34ed82dc82d8dfeba569fb15e087a",
          "sha1": "b60b9160d544ed02881aa214c139d611a0196d8b",
          "md5": "531a0c17d84a001157ee32e5fd34c7b3"
        }
      ]
    }
  ]
}
