{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "dklignzjincgpk54yjmfetzxfq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 24981,
          "sha512": "ed1db6e5de0d4209d04726aa9c75c79cad01f130e761946be12afbeb730700b203abee9601b762f62d42cf95b6230671603f7826e7651b3cdf4493f1b0491806",
          "sha256": "3c127ac0f209fc11e93cff72161caf037eb2dfe9703fb86a712a39cfb5d61f88",
          "sha1": "89bf13c92510ba3b44b8d1f174a01f630957a0cb",
          "md5": "f91184a570be09da353296e590feda5e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 24981,
          "sha512": "ed1db6e5de0d4209d04726aa9c75c79cad01f130e761946be12afbeb730700b203abee9601b762f62d42cf95b6230671603f7826e7651b3cdf4493f1b0491806",
          "sha256": "3c127ac0f209fc11e93cff72161caf037eb2dfe9703fb86a712a39cfb5d61f88",
          "sha1": "89bf13c92510ba3b44b8d1f174a01f630957a0cb",
          "md5": "f91184a570be09da353296e590feda5e"
        }
      ]
    }
  ]
}
