{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "common",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iado6bxwdbfwjkci6bmrburf2i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 28891,
          "sha512": "439e1d70b63a168913657b5537acb48c24998c61a7d93d39c3326b866492a9b81d4ea4b3290ef2d049f70f8ebfb5300e6d4951318e13b0de0ef9d14263c804f4",
          "sha256": "258adc3879f869c0be9d3f034c1316f38d184ec3a357cb41192b41c15b4fe2f8",
          "sha1": "8508e01fd6400a853d118d71f870fc5965546da6",
          "md5": "fb11ab13d4d3aa240a43d023c5108323"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kittinunf.result",
          "module": "result",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "common-master-SNAPSHOT.aar",
          "url": "common-master-SNAPSHOT.aar",
          "size": 28891,
          "sha512": "439e1d70b63a168913657b5537acb48c24998c61a7d93d39c3326b866492a9b81d4ea4b3290ef2d049f70f8ebfb5300e6d4951318e13b0de0ef9d14263c804f4",
          "sha256": "258adc3879f869c0be9d3f034c1316f38d184ec3a357cb41192b41c15b4fe2f8",
          "sha1": "8508e01fd6400a853d118d71f870fc5965546da6",
          "md5": "fb11ab13d4d3aa240a43d023c5108323"
        }
      ]
    }
  ]
}
