{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "x4mfbbcdrvdo5a2wp5edi3dnau"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-1.0.0.aar",
          "url": "dagger-workmanager-1.0.0.aar",
          "size": 20908,
          "sha512": "80ec1b98d7d5a06884776ff5a6b2a1f375ceb029e726ce64f9fe33670e6016de67d6d61230853b3c91c8835b6874d6236dfab208c5aa6e210f697bc455805151",
          "sha256": "4c76585d55eea6033d89f8b303ee47b9ade9b7e6c834e502048a80744f543d33",
          "sha1": "c502cc475a4055903e4bc3d90b536dd3154df5f5",
          "md5": "a177427e1e10c7918788d447f0d477d1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-1.0.0.aar",
          "url": "dagger-workmanager-1.0.0.aar",
          "size": 20908,
          "sha512": "80ec1b98d7d5a06884776ff5a6b2a1f375ceb029e726ce64f9fe33670e6016de67d6d61230853b3c91c8835b6874d6236dfab208c5aa6e210f697bc455805151",
          "sha256": "4c76585d55eea6033d89f8b303ee47b9ade9b7e6c834e502048a80744f543d33",
          "sha1": "c502cc475a4055903e4bc3d90b536dd3154df5f5",
          "md5": "a177427e1e10c7918788d447f0d477d1"
        }
      ]
    }
  ]
}
