{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-workmanager",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "bqfb2pg33jchncbap375hsdj74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-1.0.0.aar",
          "url": "dagger-workmanager-1.0.0.aar",
          "size": 20489,
          "sha512": "5a777835d090b48f39a541a4cc61358434c331a9c7f1f0d90ec89f753f75a4b4a996b07aca8b85fd944e6454fa95a3f798665f53ed553a1a428a3c8f41cb715a",
          "sha256": "b529a465efc91a95bb534b327a68c5acc26553212fdd1cb1020b0da8ac4d2a16",
          "sha1": "f7ea5c19766523bf8b8e7da2d9a24d715804478d",
          "md5": "5d5c13927ad104b39dc2209ff15f3d2c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "logging",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "dagger-base",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-workmanager-1.0.0.aar",
          "url": "dagger-workmanager-1.0.0.aar",
          "size": 20489,
          "sha512": "5a777835d090b48f39a541a4cc61358434c331a9c7f1f0d90ec89f753f75a4b4a996b07aca8b85fd944e6454fa95a3f798665f53ed553a1a428a3c8f41cb715a",
          "sha256": "b529a465efc91a95bb534b327a68c5acc26553212fdd1cb1020b0da8ac4d2a16",
          "sha1": "f7ea5c19766523bf8b8e7da2d9a24d715804478d",
          "md5": "5d5c13927ad104b39dc2209ff15f3d2c"
        }
      ]
    }
  ]
}
