{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dt5lnliqerfrresoqrdnovhsda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 15697,
          "sha512": "5314497ea4c4a01b52a00fb1c11711ac0fb83b4ccc0032a1d8a04d66e0297ae947c92db99549142fe13d289b2eece427313608dcafd0ae9544318fa5b99984e9",
          "sha256": "5a28f008b6fc444add2bc20b09ff7136fa12ea5eb83e71a3238abd9570c06b07",
          "sha1": "0dbb9d4dea8a8e744ba37279d46ea7933f777b80",
          "md5": "251652d7cd6e56a0dbb2df32d4db2990"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 15697,
          "sha512": "5314497ea4c4a01b52a00fb1c11711ac0fb83b4ccc0032a1d8a04d66e0297ae947c92db99549142fe13d289b2eece427313608dcafd0ae9544318fa5b99984e9",
          "sha256": "5a28f008b6fc444add2bc20b09ff7136fa12ea5eb83e71a3238abd9570c06b07",
          "sha1": "0dbb9d4dea8a8e744ba37279d46ea7933f777b80",
          "md5": "251652d7cd6e56a0dbb2df32d4db2990"
        }
      ]
    }
  ]
}
