{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "zjpshntq2bbkrhvoed74wdm5xu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 14345,
          "sha512": "af005f23991c38e2afbb033f7b78b9dd4db97b34e3f0a215abe03789a8f58eca6336dfc7d9ac249405ab9af3386a369e190bd6b4e16dcf363aa3f27118d7160c",
          "sha256": "e919621e97879341477e13f48100de612125da260c2e6a0cdf078199a80e61a0",
          "sha1": "a3cced0388ee935e12ef9746e260ff384ec1c9af",
          "md5": "987331e2a5b728aa831f45fe1e014dc2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 14345,
          "sha512": "af005f23991c38e2afbb033f7b78b9dd4db97b34e3f0a215abe03789a8f58eca6336dfc7d9ac249405ab9af3386a369e190bd6b4e16dcf363aa3f27118d7160c",
          "sha256": "e919621e97879341477e13f48100de612125da260c2e6a0cdf078199a80e61a0",
          "sha1": "a3cced0388ee935e12ef9746e260ff384ec1c9af",
          "md5": "987331e2a5b728aa831f45fe1e014dc2"
        }
      ]
    }
  ]
}
