{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "bqfb2pg33jchncbap375hsdj74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 14887,
          "sha512": "bcb1c8f2d31c376115456c3c994499e0c99936427dc41ca569e812022b3c2797783de63d9572c73dbc9141281eb5772afc4f516c65ef5b665b170cc052bb2afd",
          "sha256": "5513e68f58260791ac5a8433bccbb1b6f1580ef5559a3205ef59fed217f373da",
          "sha1": "65834a4af384c41f78f08d7c2cc3e5c9465148b1",
          "md5": "5be3e58f83beb2ea361947df275bb20e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-1.0.0.aar",
          "url": "dagger-base-1.0.0.aar",
          "size": 14887,
          "sha512": "bcb1c8f2d31c376115456c3c994499e0c99936427dc41ca569e812022b3c2797783de63d9572c73dbc9141281eb5772afc4f516c65ef5b665b170cc052bb2afd",
          "sha256": "5513e68f58260791ac5a8433bccbb1b6f1580ef5559a3205ef59fed217f373da",
          "sha1": "65834a4af384c41f78f08d7c2cc3e5c9465148b1",
          "md5": "5be3e58f83beb2ea361947df275bb20e"
        }
      ]
    }
  ]
}
