{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "shrsr7yjyjabjfsazhuotahioi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200308.161426-1.aar",
          "size": 14888,
          "sha512": "6f99ec1efe4e8f3e4150b61ae84ceb0c565ff9b691461be1dcdb595d37a36880a35b7754a053684009fca16a8a4bd56ea9a32213a603e2c9cc479da69092e2eb",
          "sha256": "22f1aa964844477caaaea6aebd4a4831c22dcb90d2f6b8f7d8b75f4685d8985a",
          "sha1": "a505c8045750542558550d0408fe0ae4647b4c9b",
          "md5": "fc7ae6dde21fbbd252f16d503de40d04"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200308.161426-1.aar",
          "size": 14888,
          "sha512": "6f99ec1efe4e8f3e4150b61ae84ceb0c565ff9b691461be1dcdb595d37a36880a35b7754a053684009fca16a8a4bd56ea9a32213a603e2c9cc479da69092e2eb",
          "sha256": "22f1aa964844477caaaea6aebd4a4831c22dcb90d2f6b8f7d8b75f4685d8985a",
          "sha1": "a505c8045750542558550d0408fe0ae4647b4c9b",
          "md5": "fc7ae6dde21fbbd252f16d503de40d04"
        }
      ]
    }
  ]
}
