{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2qyg3riynbenzdtrablltx2xni"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14799,
          "sha512": "846afc44c08cfbbc03ae7e122e9a4a700b71c233f0007dc0d78c1a095308b539950d79a6796b2fbdec0cf86255910869fe2477fc0b3b394eb2ce411a6fa6c8f6",
          "sha256": "509fd3eea1407091c2d5d6ff1488d83327e7f2d513eb05d1ed52269355d7914a",
          "sha1": "19df53d7c73c58bf9c31af13ecf09f406fcba21e",
          "md5": "8187b45daac214d02f9641265d1a2b99"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14799,
          "sha512": "846afc44c08cfbbc03ae7e122e9a4a700b71c233f0007dc0d78c1a095308b539950d79a6796b2fbdec0cf86255910869fe2477fc0b3b394eb2ce411a6fa6c8f6",
          "sha256": "509fd3eea1407091c2d5d6ff1488d83327e7f2d513eb05d1ed52269355d7914a",
          "sha1": "19df53d7c73c58bf9c31af13ecf09f406fcba21e",
          "md5": "8187b45daac214d02f9641265d1a2b99"
        }
      ]
    }
  ]
}
