{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "jmxjev3p6fc6bbr74rhltycrqi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14798,
          "sha512": "fb7fb782e794602b61acc8559166b7ee988642dab8288fe7e232ecd0f89a29e31e7517e7299f5367f33611b996ef841ecfe513ed977426230754e45d7287fb7d",
          "sha256": "858c6cbde65d1b612794c2100a97731a33c6e19498515d167fd48a0dab332a42",
          "sha1": "b6e5ae9932ffe6a74871ec515a7dcf7bb357bb9b",
          "md5": "e178b0082f7f62487549ec36bccb9c95"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14798,
          "sha512": "fb7fb782e794602b61acc8559166b7ee988642dab8288fe7e232ecd0f89a29e31e7517e7299f5367f33611b996ef841ecfe513ed977426230754e45d7287fb7d",
          "sha256": "858c6cbde65d1b612794c2100a97731a33c6e19498515d167fd48a0dab332a42",
          "sha1": "b6e5ae9932ffe6a74871ec515a7dcf7bb357bb9b",
          "md5": "e178b0082f7f62487549ec36bccb9c95"
        }
      ]
    }
  ]
}
