{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "t2h2c5f6p5cwfgptdtutrjndli"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200307.150336-1.aar",
          "size": 14416,
          "sha512": "2e997c4aa087fb7b14a50404810cef078e5fc22cc076a94f6c39941768a6359f8af5f9f4709b2a0d3fd09c40419f3e5dc754013577a27e452c63543a96eb5ff7",
          "sha256": "9dbe807c21895ea654d64f223f2542d29af2f5507a25e94c341a8d4a8e5b7347",
          "sha1": "53cebf7c96d530060c7936355516348694bc5e46",
          "md5": "522e00601baf9df708a196a35bdac286"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200307.150336-1.aar",
          "size": 14416,
          "sha512": "2e997c4aa087fb7b14a50404810cef078e5fc22cc076a94f6c39941768a6359f8af5f9f4709b2a0d3fd09c40419f3e5dc754013577a27e452c63543a96eb5ff7",
          "sha256": "9dbe807c21895ea654d64f223f2542d29af2f5507a25e94c341a8d4a8e5b7347",
          "sha1": "53cebf7c96d530060c7936355516348694bc5e46",
          "md5": "522e00601baf9df708a196a35bdac286"
        }
      ]
    }
  ]
}
