{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "oqvocydmkrbzpjpbm3omis5pza"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 15785,
          "sha512": "9e395773e3629a215983b90ff698c860580faa7dd9fb1a8220d32ff01df3c540bcf066200b34364b0f4fefb01ce9f5f3d83e9af374c16326d1e98bd4eb73002e",
          "sha256": "89a7c0654c43330be84f0660fbb8eaecba3a4fec05805c967691271602f2d4f2",
          "sha1": "cab68fd3210983fb76db1170ead6559b0ce9ae12",
          "md5": "80790c8f09515042d1b6e8781a76bf4e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 15785,
          "sha512": "9e395773e3629a215983b90ff698c860580faa7dd9fb1a8220d32ff01df3c540bcf066200b34364b0f4fefb01ce9f5f3d83e9af374c16326d1e98bd4eb73002e",
          "sha256": "89a7c0654c43330be84f0660fbb8eaecba3a4fec05805c967691271602f2d4f2",
          "sha1": "cab68fd3210983fb76db1170ead6559b0ce9ae12",
          "md5": "80790c8f09515042d1b6e8781a76bf4e"
        }
      ]
    }
  ]
}
