{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "lzvivyt2fzgn7d2tllggsgdija"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14807,
          "sha512": "f0074e2a4aa416cdd0f9e09edf92d0220461733952f6991c8b3380d2538d4728463896ec6f13f79eacb959f9838d0c6c558d1857b3a607e9ce033d9c6bdfa8e4",
          "sha256": "b089291a55e6a98d8f5a3bb8978edf0699208169955c3df7be00ae9447d45b3a",
          "sha1": "717606a8df31c6e553596d68f131caf695986d6c",
          "md5": "27aba9b880d32a7a1668253e1b404e01"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-SNAPSHOT.aar",
          "size": 14807,
          "sha512": "f0074e2a4aa416cdd0f9e09edf92d0220461733952f6991c8b3380d2538d4728463896ec6f13f79eacb959f9838d0c6c558d1857b3a607e9ce033d9c6bdfa8e4",
          "sha256": "b089291a55e6a98d8f5a3bb8978edf0699208169955c3df7be00ae9447d45b3a",
          "sha1": "717606a8df31c6e553596d68f131caf695986d6c",
          "md5": "27aba9b880d32a7a1668253e1b404e01"
        }
      ]
    }
  ]
}
