{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "dagger-base",
    "version": "master-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "a5uvm6i2erewro6aj65fk6ppsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200127.112201-3.aar",
          "size": 14338,
          "sha512": "27f8a33c5037c64ed72835ea88004f3e4ee13b735d0edc47c1f6651b2cb2516b806297ca43cc6b827ec46383cc8322c669ad20f1206a86425011b2fdf61b537b",
          "sha256": "e8b47119542d515cc62014a53f57497a7cb11248aed42189fcc6dba3e3fa5000",
          "sha1": "69184ffde8b8efe99f93da3d9612cd895356bcb2",
          "md5": "5a799cfcc443ce10b535f15c42b7ab22"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dagger-base-master-SNAPSHOT.aar",
          "url": "dagger-base-master-20200127.112201-3.aar",
          "size": 14338,
          "sha512": "27f8a33c5037c64ed72835ea88004f3e4ee13b735d0edc47c1f6651b2cb2516b806297ca43cc6b827ec46383cc8322c669ad20f1206a86425011b2fdf61b537b",
          "sha256": "e8b47119542d515cc62014a53f57497a7cb11248aed42189fcc6dba3e3fa5000",
          "sha1": "69184ffde8b8efe99f93da3d9612cd895356bcb2",
          "md5": "5a799cfcc443ce10b535f15c42b7ab22"
        }
      ]
    }
  ]
}
