{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arunkumar.android",
    "module": "preferences",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dt5lnliqerfrresoqrdnovhsda"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-rx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "rxjava",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        }
      ],
      "files": [
        {
          "name": "preferences-1.0.0.aar",
          "url": "preferences-1.0.0.aar",
          "size": 115673,
          "sha512": "6a04ec66873841e8fd3fb8affac6bc04f7b76f89a021c0a679c9bccfbeb7eaab1d2eb6986006a280db90df89820bcc4b4b5adbcfefaaf33f4cade3e0d982d810",
          "sha256": "7ae0d2841dc10f68c3eabe3d2f45e4c2203740cc65087dca1c949cb3b4001b5c",
          "sha1": "47e18dc5e048ad0ae0aef45e0b14806e2e6b4238",
          "md5": "ee6d0e0ed430c32e2d2d739a8208b043"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arunkumar.android",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.arunkumar.android",
          "module": "epoxy-rx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "epoxy",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.afollestad.rxkprefs",
          "module": "rxjava",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.23.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "preferences-1.0.0.aar",
          "url": "preferences-1.0.0.aar",
          "size": 115673,
          "sha512": "6a04ec66873841e8fd3fb8affac6bc04f7b76f89a021c0a679c9bccfbeb7eaab1d2eb6986006a280db90df89820bcc4b4b5adbcfefaaf33f4cade3e0d982d810",
          "sha256": "7ae0d2841dc10f68c3eabe3d2f45e4c2203740cc65087dca1c949cb3b4001b5c",
          "sha1": "47e18dc5e048ad0ae0aef45e0b14806e2e6b4238",
          "md5": "ee6d0e0ed430c32e2d2d739a8208b043"
        }
      ]
    }
  ]
}
